#----------------------------------------------------------------------
#pyclone_008_make_cloneevol_input.R
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#load functions and libraries
#----------------------------------------------------------------------

options(stringsAsFactors=F)

#load libraries
packages <- c("dplyr", "readr", "ggplot2", "vcfR", "tidyr", "mclust", "data.table",
              "plyr", "clonevol", "readxl", "pheatmap",
              "ggrepel", "stringr", "maftools", "magrittr", "ggExtra", "cowplot")
lapply(packages, require, character.only = TRUE)

date = Sys.Date()

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#use pyclone clustering results from small subset of mutations to
#generate tree

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#Our mutations
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/merged_MUTECT2_STRELKA/merged_variants_vcfs/vcf_summary_text")
read_only = readRDS(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.rds")[length(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.rds"))])

setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
#sample info
samps = readRDS("/cluster/projects/kridelgroup/RAP_ANALYSIS/copy_RAP_masterlist_samples.rds")
colnames(samps)[4] ="Indiv"
z = which(samps$Indiv %in% read_only$Indiv)
samps = samps[z,]
samps = samps %>% select(STUDY_PATIENT_ID, Indiv)
samps = merge(samps, read_only, by = "Indiv")
colnames(samps)[1] = "samplename"

#DLBCL driver genes from Reddy et al 2017
reddy = as.data.table(read_excel("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/Reddyetal_2017_driver_mutations.xlsx"))

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#results from pyclone-vi
patients= c("LY_RAP_0001", "LY_RAP_0002", "LY_RAP_0003")

#patient = "LY_RAP_0002" #test

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

get_patient_pyclone_plot = function(patient){

  #get results from pyclone
  file_name = paste(patient, "_rap_wgs_all_muts.tsv", sep="")
  vi=fread(file_name)

  #summary of mutation data
  mut_gene = unique(read_only[,c("mut_id", "symbol", "biotype", "Func.ensGene", "ExonicFunc.ensGene",
    "AAChange.ensGene", "cosmic68", "STUDY_PATIENT_ID")])
  mut_gene = as.data.table(filter(mut_gene, STUDY_PATIENT_ID == patient))
  mut_gene = unique(mut_gene[,c("mut_id", "symbol", "biotype", "Func.ensGene", "ExonicFunc.ensGene",
    "AAChange.ensGene", "cosmic68")])

  #pyclone_file= fread(files)
  pyclone_file=vi

  #how many mutations in each cluster?
  cluster_sum = unique(pyclone_file[,c("cluster_id", "mutation_id")])

  if(patient == "LY_RAP_0001"){
    cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=10)
    pyclone_remove=c()
  }

  if(patient == "LY_RAP_0002"){
    cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=100)
    #remove clusters with low cluster_assignment_prob
    #pyclone_remove = unique(as.data.table(filter(pyclone_file, (cluster_assignment_prob < 0.5) | (is.na(cellular_prevalence_std))))$cluster_id)
    pyclone_remove=c()
  }

  if(patient == "LY_RAP_0003"){
    cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=400)
    #remove clusters with low cluster_assignment_prob
    pyclone_remove = unique(as.data.table(filter(pyclone_file, (cluster_assignment_prob < 0.5) | (is.na(cellular_prevalence_std))))$cluster_id)
  }

  pyclone_file = filter(pyclone_file, cluster_id %in% cluster$V1, !(cluster_id %in% pyclone_remove))
  colnames(pyclone_file)[1] = "mut_id"
  pyclone_file_merged = merge(pyclone_file, mut_gene, by="mut_id")

  #ClonEvol requires an input data frame consisting of at least a
  #cluster column and one or more variant cellular prevalence columns,
  #each corresponds to a sample.
  samps = as.data.frame(unique(pyclone_file_merged$sample_id))
  colnames(samps)[1] = "sample_id"
  samps$sample = ""

  if(patient == "LY_RAP_0001"){
    samps$sample = c(
      "Mediastinal_lymph_node",
      "Aorta_abdominal",
      "Aorta_ascending")
    }

  if(patient == "LY_RAP_0002"){
    samps$sample = c(
      "Left_lobe_liver",
      "Mesenteric_lymph_node",
      "Thorax",
      "Adrenal_gland")
    }

  if(patient == "LY_RAP_0003"){
    samps$sample = c(
      "FFPE_left_axilla_LN",
      "FFPE_left_breast",
      "FFPE_right_neck_LN",
      "FT_Abdomen",
      "FT_Adrenal_gland",
      "FT_Axilla",
      "FT_Bladder",
      "FT_Cecum",
      "FT_Cervical_lymph_node",
      "FT_Inguinal_region",
      "FT_Kidney_NOS_341360",
      "FT_Kidney_NOS_341364",
      "FT_Mediastinum",
      "FT_Omentum",
      "FT_Pancreas",
      "FT_Parotid_gland",
      "FT_Retroperitoneum",
      "FT_Shoulder",
      "FT_Spleen",
      "FT_Stomach")}

  pyclone_file_merged = merge(pyclone_file_merged, samps, by="sample_id")
  pyclone_file_merged$vaf_fixed = pyclone_file_merged$cellular_prevalence /2 *100

  summaries_vafs_fixed = as.data.table(pyclone_file_merged %>%
    group_by(sample, cluster_id) %>%
    dplyr::summarize(mean=mean(cellular_prevalence)))

  summaries_vafs_fixed = dcast(summaries_vafs_fixed, sample ~ cluster_id,
      value.var = "mean")

  rownames(summaries_vafs_fixed) = summaries_vafs_fixed$sample
  summaries_vafs_fixed$sample = NULL
  summaries_vafs_fixed = as.matrix(summaries_vafs_fixed)
  col<- colorRampPalette(c("red", "white", "blue"))(256)
  pdf(paste(patient, "heatmap_clusters_summary.pdf", sep="_"), width=10, height=10)
  pheatmap(summaries_vafs_fixed, cutree_cols=3)
  dev.off()

  #for each cluster and sample get mean cell prev
  mean_cp_clusters = as.data.table(pyclone_file_merged %>% group_by(sample_id, cluster_id) %>%
  dplyr::summarize(mean_cp=mean(cellular_prevalence)))
  mean_cp_clusters$cluster_id = factor(mean_cp_clusters$cluster_id)
  mean_cp_clusters$sample_name = sapply(mean_cp_clusters$sample_id,
    function(x){unlist(strsplit(x, "_subset_muts_pyclone_input"))[1]})
  mean_cp_clusters = mean_cp_clusters[order(-mean_cp)]
  mean_cp_clusters$cluster_id = factor(mean_cp_clusters$cluster_id, levels=unique(mean_cp_clusters$cluster_id))

  input = dcast(pyclone_file_merged, mut_id + symbol + cluster_id ~ sample,
    value.var = "vaf_fixed")
  input$is.driver = ""
  z = which(input$symbol %in% reddy$Gene)
  input$is.driver[z] = TRUE
  input$is.driver[-z] = FALSE
  input$cluster_id = as.numeric(input$cluster_id)
  input = as.data.table(input)
  input = input[order(cluster_id)]
  clusts = as.data.frame(unique(input$cluster_id)) ; colnames(clusts)="cluster_id"
  clusts$cluster = 1:nrow(clusts)
  input = merge(input, clusts, by = "cluster_id")
  dat=input
  dat$cluster = as.character(dat$cluster)

  #visualizing clusters

  library(RColorBrewer)
  n <- 20
  qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
  col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

  dat$is.driver = as.logical(dat$is.driver)

  pdf(paste(patient,'box.pdf', sep="_"), width = 5, height = 7, useDingbats = FALSE, title='')

  if(patient == "LY_RAP_0001"){
    vafs_cols = colnames(dat)[4:6]}

  if(patient == "LY_RAP_0002"){
    vafs_cols = colnames(dat)[4:7]}

  if(patient == "LY_RAP_0003"){
    vafs_cols = colnames(dat)[4:23]}

  pp <-plot.variant.clusters(dat,
    cluster.col.name ='cluster',
    cluster.size.text.color ='blue',
    vaf.col.names = vafs_cols,
    vaf.limits = 75,
    sample.title.size = 5,
    violin = FALSE,
    box = FALSE,
    jitter = TRUE,
    jitter.color = col_vector,
    jitter.shape = 1,
    highlight ='is.driver',
    highlight.shape = 21,
    highlight.color ='blue',
    highlight.fill.color ='green',
    highlight.note.col.name ='symbol',
    highlight.note.size = 1,
    jitter.size = 1,
    jitter.alpha = 1,
    jitter.center.method ='median',
    jitter.center.size = 1,
    jitter.center.color ='darkgray',
    jitter.center.display.value ='none',
    order.by.total.vaf = TRUE)

    dev.off()

    summ_dlbcl = unique(filter(dat, is.driver == TRUE) %>% select(symbol, cluster))

    pdf(paste(patient,'flow.pdf', sep="_"), width=10, height=5, useDingbats=FALSE, title='')
      plot.cluster.flow(dat, vaf.col.names = vafs_cols,
          colors = col_vector)
    dev.off()

    print("done making pyclone summary plots")
}#end function patient input

get_patient_pyclone_plot("LY_RAP_0001")
get_patient_pyclone_plot("LY_RAP_0002")

#llply(patients, get_patient_pyclone_plot)























#change cluster 1 so it's not 100 cell prevalence
#z = which(dat$cluster==1)
#dat$FFPE_right_neck_LN[z] = 98

#to make tree need to have founding clone be labelled 1
#so remove the first cluster since ignoring it anyways
if(patient == "LY_RAP_0001"){
z = which(dat$cluster==1)
dat$cluster[z] = 8
z = which(dat$cluster==7)
dat$cluster[z] = 1
z = which(dat$cluster==8)
dat$cluster[z] = 7
#z = which(dat$cluster==3)
#dat$cluster[z] = 2
#z = which(dat$cluster==4)
#dat$cluster[z] = 3
#z = which(dat$cluster==5)
#dat$cluster[z] = 4
#z = which(dat$cluster==6)
#dat$cluster[z] = 5
#z = which(dat$cluster==7)
#dat$cluster[z] = 6
}

#z = which(dat$cluster==11)
#dat$cluster[z] = 10

#infer clonal evolution tree
y = infer.clonal.models(variants = dat,
  cluster.col.name ='cluster',
vaf.col.names = vafs_cols,
cancer.initiation.model='monoclonal',
#subclonal.test ='none',
subclonal.test = 'bootstrap',
subclonal.test.model ='non-parametric',
num.boots = 1000,
ignore.clusters=c(2,7),
#score.model.by = 'metap',
cluster.center ='mean', min.cluster.vaf = 0,
          sum.p = 0.05,
          alpha = 0.05, founding.cluster = 1,
clone.colors = col_vector)

#y <-transfer.events.to.consensus.trees(y,dat[dat$is.driver,],
#  cluster.col.name ='cluster',event.col.name ='symbol')

y <-convert.consensus.tree.clone.to.branch(y, branch.scale ='sqrt')

pdf('trees.pdf', width = 3, height = 5, useDingbats = FALSE)
plot.all.trees.clone.as.branch(y)
dev.off()

plot.clonal.models(y,
  # box plot parameters
  box.plot = TRUE,
  #fancy.boxplot = TRUE,
  #fancy.variant.boxplot.highlight ='is.driver',
  #fancy.variant.boxplot.highlight.shape = 21,
  #fancy.variant.boxplot.highlight.fill.color ='red',
  fancy.variant.boxplot.highlight.color ='black',
  #fancy.variant.boxplot.highlight.note.col.name ='symbol',
  fancy.variant.boxplot.highlight.note.color ='blue',
  fancy.variant.boxplot.highlight.note.size = 1,
fancy.variant.boxplot.jitter.alpha = 1, fancy.variant.boxplot.jitter.center.color ='grey50',
fancy.variant.boxplot.base_size = 5, fancy.variant.boxplot.plot.margin = 1,
fancy.variant.boxplot.vaf.suffix ='.VAF',
# bell plot parameters
clone.shape ='bell',bell.event = TRUE, bell.event.label.color ='blue',
bell.event.label.angle = 60, clone.time.step.scale = 1, bell.curve.step = 2,
# node-based consensus tree parameters
merged.tree.plot = TRUE,tree.node.label.split.character = NULL,
tree.node.shape ='circle',tree.node.size = 20,tree.node.text.size = 0.5,
merged.tree.node.size.scale = 1.25,merged.tree.node.text.size.scale = 2.5,
merged.tree.cell.frac.ci = FALSE,
# branch-based consensus tree parameters
merged.tree.clone.as.branch = TRUE,mtcab.event.sep.char =',',
mtcab.branch.text.size = 1,
mtcab.branch.width = 0.75,mtcab.node.size = 2,mtcab.node.label.size = 1,
mtcab.node.text.size = 1.5,
# cellular population parameters
cell.plot = TRUE,num.cells = 100,cell.border.size = 0.25,
cell.border.color ='black',clone.grouping ='horizontal',
#meta-parameters
scale.monoclonal.cell.frac = TRUE,show.score = FALSE,cell.frac.ci = TRUE,
disable.cell.frac = FALSE,
# output figure parameters
out.dir ='output',out.format ='pdf',overwrite.output = TRUE,
width = 35,height = 30)

#mut info
mut_info = merge(mut_gene, dat, by=c("mut_id", "symbol"))
library(openxlsx)
write.xlsx(mut_info, 'Pyclone-VI-clonevol-results.xlsx')

#save input data required for mapscape
#adjacency matrix
#make manually for now

#cp values mean per cluster
mean_cps = melt(dat, id.vars = c("cluster", "cluster_id", "mut_id", "symbol", "is.driver")) %>%
select(cluster,variable, value)

mean_cps = as.data.table(mean_cps %>% group_by(variable, cluster) %>%
dplyr::summarize(mean_cp=mean(value)))

#convert back from VAF to CCF
mean_cps$mean_cp = mean_cps$mean * 2 / 100
colnames(mean_cps) = c("sample_id" ,"clone_id", "clonal_prev")
write.table(mean_cps, file=paste(date, "_clonevol_output_for_mapscape.txt", sep=""), quote=F, row.names=F, sep="\t")

#-----
#DONE-
#-----
