#-------------------------------------------------------------------------------
#pyclone-vi_005_pyclone_mutation_signatures_in_clusters.R
#Karin Isaev
#March 3rd 2021, 2021
#load R/4.0.0
#-------------------------------------------------------------------------------

#load packages and data
source("/cluster/home/kisaev/RAP_WGS/config-file.R")
library("gplots")
#library(MutationalPatterns)
library(BSgenome)
ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)
library(NMF)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(biomaRt)
library(GenomicRanges)
library(maftools)
#Requires BSgenome object
library(BSgenome.Hsapiens.UCSC.hg19, quietly = TRUE)
#library(logr)
library('pheatmap')

library(dplyr)
library(reshape2)
#library(kableExtra)
library(ggplot2)
library(gridExtra)
library(BSgenome.Hsapiens.UCSC.hg19)
hg19 <- BSgenome.Hsapiens.UCSC.hg19
library(ggpubr)

# Load mutSignatures
#library(mutSignatures)
library(MutationalPatterns)

ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#set up patients
patients= c("LY_RAP_0001", "LY_RAP_0002", "LY_RAP_0003")

#test
#patient = "LY_RAP_0003"

z = which(read_only$Tissue_Site == "Aorta, ascending, not specified \n\n")
if(!(length(z) == 0)){
read_only$Tissue_Site[z] = "Aorta, ascending"}

#pyclone input files
p001_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0001_pyclone_input.tsv")
p002_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0002_pyclone_input.tsv")
p003_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0003_pyclone_input.tsv")

#pyclone output files
p001_pyclone_output = fread("10-06-2021/all_samples_pyclonevi_LY_RAP_0001_beta-binomial_rap_wgs_all_muts.tsv")
p002_pyclone_output = fread("10-06-2021/all_samples_pyclonevi_LY_RAP_0002_beta-binomial_rap_wgs_all_muts.tsv")
p003_pyclone_output = fread("10-06-2021/all_samples_pyclonevi_LY_RAP_0003_beta-binomial_rap_wgs_all_muts.tsv")

#pairtree clusters - files made manually
p001_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-11_input_files/results2/p001_pairtree_clones.txt")
p002_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-11_input_files/results2/p002_pairtree_clones.txt")
p003_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-11_input_files/results2/p003_pairtree_clones.txt")

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#use pyclone results clusters to identify mutation signatures associated
#with different clones

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#add categories for CNAs
read_only$CNA = ""

#LOH
z = which((read_only$ntot ==  read_only$Nmaj) & (read_only$ntot >= 2))
read_only$CNA[z] = "Somatic LOH"

#Neutral
z = which((read_only$ntot !=  read_only$Nmaj) & (read_only$ntot == 2))
read_only$CNA[z] = "Neutral"

#Deletions
z = which((read_only$ntot ==  read_only$Nmaj) & (read_only$ntot == 0))
read_only$CNA[z] = "Homozygous Del"

z = which((read_only$ntot ==  read_only$Nmaj) & (read_only$ntot == 1))
read_only$CNA[z] = "Hemizygous Del"

#Amplications
z = which((read_only$CNA == "") & (read_only$ntot > 5))
read_only$CNA[z] = ">5_N_Gain"

z = which(read_only$CNA == "")
read_only$CNA[z] = paste(read_only$ntot[z], "_N_", "Gain", sep="")

z = which(is.na(read_only$ntot))
if(!(length(z) == 0)){
  read_only=read_only[-z,]
}

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

patient= patients[3]
pyclone_output = p003_pyclone_output
pairtree_cluster = p003_pairtree

get_pyclone_summ = function(patient, pyclone_output, pairtree_cluster){

  #read in mutation data for each cluster as obtained from pyclone
  muts <- pyclone_output

  #get clusters
  clusters = unique(muts$cluster_id)

  #for each cluster gather mutations and their details from main mutation
  #file

  cluster_muts = unique(muts[,c("mutation_id", "cluster_id")])

  t = as.data.table(table(cluster_muts$cluster_id))
  t = filter(t, N >30)
  muts_keep = filter(cluster_muts, cluster_id %in% t$V1)
  colnames(t)= c("cluster_id", "num_muts")

  if(patient == "LY_RAP_0003"){
    t$num_muts[t$cluster_id == 4] = 93
  }

  t=merge(t, pairtree_cluster)
  colnames(t)[3] = "pairtree_cluster_name"
  t$cluster_id = as.numeric(t$cluster_id)

  muts_keep = merge(muts_keep, t, by="cluster_id")

  muts = unique(muts[,c("sample_id", "mutation_id", "cluster_id", "cellular_prevalence")])
  muts = merge(muts, t, by="cluster_id")

  colnames(muts)[2:3] = c("Sample", "mut_id")
  muts = merge(muts, read_only, by=c("Sample", "mut_id"))
  muts = unique(muts[,c("Sample", "mut_id", "pairtree_cluster_name", "cellular_prevalence",
"gt_AF", "Nmin", "Nmaj", "Ploidy", "Purity", "Tissue_Site")])

  ggdensity(muts, x = "gt_AF",
 color = "Sample", palette = mypal, facet.by="pairtree_cluster_name")

}
