#----------------------------------------------------------------------
#setting_up_CITUP.R
#karin isaev
#last updated: July 2nd 2019
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#load functions and libraries 
#----------------------------------------------------------------------

options(stringsAsFactors=F)

#load libraries 
packages <- c("dplyr", "readr", "ggplot2", "vcfR", "tidyr", "mclust", "data.table", 
              "plyr", 
              "ggrepel", "stringr", "maftools", "magrittr", "ggExtra", "cowplot")
lapply(packages, require, character.only = TRUE)

date = Sys.Date()

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#using output data tables from pyclone
#let's plot VAfs of T1 versus T2 
#these output files were generated using the script --> pyclone_run_analysis.sh

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
files = list.files(pattern="table_file.txt")

#data - table generated by pyclone (cluster)
files_cluster = list.files(pattern="cluster.txt")

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

pyclone_file= fread(files)
  
#how many mutations in each cluster?
cluster_sum = unique(pyclone_file[,c("cluster_id", "mutation_id")])
  
cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=2)
  
#let's keep only the clusters with more than two mutations in them 
pyclone_file = filter(pyclone_file, cluster_id %in% cluster$V1)

muts = dcast(pyclone_file, cluster_id + mutation_id ~ sample_id, value.var = "cellular_prevalence")
clusters = muts[,c(1:2)] 

#mutation file
muts_final = muts[,c(3:ncol(muts))]
file = paste(date, "rap_citup_input_freqs.txt", sep="_")
write.table(muts_final, file, quote=F, row.names=F, col.names=F, sep="\t")
  
#cluster file
clusters = muts[,c("cluster_id")]
file = paste(date, "rap_citup_input_clusters.txt", sep="_")
write.table(clusters, file, quote=F, row.names=F, col.names=F, sep="\t")

#-----
#DONE-
#-----








