#-------------------------------------------------------------------------------
#pyclone-vi_003_make_cloneevol_input_all_muts.R
#Karin Isaev
#Monday March 1st 2021, 2021
#load R/3.5.0
#-------------------------------------------------------------------------------

#load packages and data
source("/cluster/home/kisaev/RAP_WGS/config-file.R")
library(clonevol)
library("gplots")

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#set up patients
patients= c("LY_RAP_0001", "LY_RAP_0002", "LY_RAP_0003")

#test
patient = "LY_RAP_0003"

z = which(read_only$Tissue_Site == "Aorta, ascending, not specified \n\n")
if(!(length(z) == 0)){
read_only$Tissue_Site[z] = "Aorta, ascending"}

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

get_patient_pyclone_plot = function(patient){

  #get results from pyclone
  file_name = paste(patient, "_rap_wgs_all_muts.tsv", sep="")
  vi=fread(file_name)

  #summary of mutation data
  mut_gene = unique(read_only[,c("mut_id", "symbol", "biotype", "Func.ensGene", "ExonicFunc.ensGene",
    "AAChange.ensGene", "cosmic68", "STUDY_PATIENT_ID")])
  mut_gene = as.data.table(filter(mut_gene, STUDY_PATIENT_ID == patient))
  mut_gene = unique(mut_gene[,c("mut_id", "symbol", "biotype", "Func.ensGene", "ExonicFunc.ensGene",
    "AAChange.ensGene", "cosmic68")])

  #pyclone_file= fread(files)
  pyclone_file=vi

  #how many mutations in each cluster?
  cluster_sum = unique(pyclone_file[,c("cluster_id", "mutation_id")])

  if(patient == "LY_RAP_0001"){
    cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=20)
    pyclone_remove=c()
  }

  if(patient == "LY_RAP_0002"){
    cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=100)
    #remove clusters with low cluster_assignment_prob
    #pyclone_remove = unique(as.data.table(filter(pyclone_file, (cluster_assignment_prob < 0.5) | (is.na(cellular_prevalence_std))))$cluster_id)
    pyclone_remove=c()
  }

  if(patient == "LY_RAP_0003"){
    cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=100)
    #remove clusters with low cluster_assignment_prob
    #pyclone_remove = unique(as.data.table(filter(pyclone_file, (cluster_assignment_prob < 0.5) | (is.na(cellular_prevalence_std))))$cluster_id)
    pyclone_remove=c()
  }

  pyclone_file = filter(pyclone_file, cluster_id %in% cluster$V1, !(cluster_id %in% pyclone_remove))
  colnames(pyclone_file)[1] = "mut_id"
  pyclone_file_merged = merge(pyclone_file, mut_gene, by="mut_id")

  #ClonEvol requires an input data frame consisting of at least a
  #cluster column and one or more variant cellular prevalence columns,
  #each corresponds to a sample.
  samps = as.data.frame(unique(pyclone_file_merged$sample_id))
  colnames(samps)[1] = "sample_id"
  samps$sample = ""

  for(i in 1:length(unique(samps$sample_id))){
    print(i)
    tissue = read_only$Tissue_Site[read_only$Sample == samps$sample_id[i]][1]
    tissue = print(paste(unlist(strsplit(tissue, ", ")), collapse="_"))
    tissue=print(paste(unlist(strsplit(tissue, " ")), collapse="_"))
    samps$sample[i] = tissue
  }

  pyclone_file_merged = merge(pyclone_file_merged, samps, by="sample_id")
  pyclone_file_merged$vaf_fixed = pyclone_file_merged$cellular_prevalence /2 *100

  summaries_vafs_fixed = as.data.table(pyclone_file_merged %>%
    group_by(sample, cluster_id) %>%
    dplyr::summarize(mean=mean(cellular_prevalence)))

  summaries_vafs_fixed = dcast(summaries_vafs_fixed, sample ~ cluster_id,
      value.var = "mean")

  rownames(summaries_vafs_fixed) = summaries_vafs_fixed$sample
  summaries_vafs_fixed$sample = NULL
  summaries_vafs_fixed = as.matrix(summaries_vafs_fixed)
  col<- colorRampPalette(c("red", "white", "blue"))(256)

  #for each cluster and sample get mean cell prev
  mean_cp_clusters = as.data.table(pyclone_file_merged %>% group_by(sample_id, cluster_id) %>%
  dplyr::summarize(mean_cp=mean(cellular_prevalence)))
  mean_cp_clusters$cluster_id = factor(mean_cp_clusters$cluster_id)
  mean_cp_clusters$sample_name = sapply(mean_cp_clusters$sample_id,
    function(x){unlist(strsplit(x, "_all_muts_pyclone_input"))[1]})
  mean_cp_clusters = mean_cp_clusters[order(-mean_cp)]
  mean_cp_clusters$cluster_id = factor(mean_cp_clusters$cluster_id, levels=unique(mean_cp_clusters$cluster_id))

  input = dcast(pyclone_file_merged, mut_id + symbol + cluster_id ~ sample,
    value.var = "vaf_fixed")
  input$is.driver = ""

  if(patient == "LY_RAP_0001"){
  z = which(input$symbol %in% all_drivers$Gene[all_drivers$type == "MCL"])}

  if(patient == "LY_RAP_0002"){
  z = which(input$symbol %in% all_drivers$Gene[all_drivers$type == "PMBCL"])}

  if(patient == "LY_RAP_0003"){
  z = which(input$symbol %in% all_drivers$Gene[all_drivers$type == "DLBCL"])}

  input$is.driver[z] = TRUE
  input$is.driver[-z] = FALSE
  input$cluster_id = as.numeric(input$cluster_id)
  input = as.data.table(input)
  input = input[order(cluster_id)]
  clusts = as.data.frame(unique(input$cluster_id)) ; colnames(clusts)="cluster_id"
  clusts$cluster = 1:nrow(clusts)
  input = merge(input, clusts, by = "cluster_id")
  dat=input
  dat$cluster = as.character(dat$cluster)

  #visualizing clusters

  library(RColorBrewer)
  n <- 20
  qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
  col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

  dat$is.driver = as.logical(dat$is.driver)

  if(patient == "LY_RAP_0001"){
    pdf(paste(patient,'all_mutations_box.pdf', sep="_"), width = 8, height = 10, useDingbats = FALSE, title='')
    vafs_cols = colnames(dat)[4:6]}

  if(patient == "LY_RAP_0002"){
    pdf(paste(patient,'all_mutations_box.pdf', sep="_"), width = 8, height = 10, useDingbats = FALSE, title='')
    vafs_cols = colnames(dat)[4:7]}

  if(patient == "LY_RAP_0003"){
    pdf(paste(patient,'all_mutations_box.pdf', sep="_"), width = 20, height = 20, useDingbats = FALSE, title='')
    vafs_cols = colnames(dat)[4:23]}

  pp <-plot.variant.clusters(dat,
    cluster.col.name ='cluster',
    cluster.size.text.color ='blue',
    vaf.col.names = vafs_cols,
    vaf.limits = 75,
    sample.title.size = 5,
    violin = FALSE,
    box = FALSE,
    jitter = TRUE,
    jitter.color = col_vector,
    jitter.shape = 1,
    #highlight ='is.driver',
    highlight.shape = 21,
    highlight.color ='blue',
    highlight.fill.color ='green',
    highlight.note.col.name ='symbol',
    highlight.note.size = 1,
    jitter.size = 1,
    jitter.alpha = 1,
    jitter.center.method ='median',
    jitter.center.size = 1,
    jitter.center.color ='darkgray',
    jitter.center.display.value ='none',
    order.by.total.vaf = TRUE)

    dev.off()

    summ_dlbcl = unique(filter(dat, is.driver == TRUE) %>% select(symbol, cluster))

    pdf(paste(patient,'all_mutations_flow.pdf', sep="_"), width=10, height=5, useDingbats=FALSE, title='')
      plot.cluster.flow(dat, vaf.col.names = vafs_cols,
          colors = col_vector)
    dev.off()

    print("done making pyclone summary plots")

    if(patient == "LY_RAP_0001"){

      z1=which(dat$cluster == 1)
      z2=which(dat$cluster == 6)
      dat$cluster[z1] = 6
      dat$cluster[z2] = 1

      dat[which(dat$cluster==1),][,4:6] = 50

      z = which(dat$cluster==2)
      dat$Mediastinal_lymph_node[z] = 49
      dat$Aorta_ascending[z] = 49

      z = which(dat$cluster==7)
      dat$Mediastinal_lymph_node[z] = 48
      dat$Aorta_ascending[z] = 48

      z = which(dat$cluster==3)
      dat$Aorta_abdominal_not_specified[z] = 27.5

      clusters_remove=c(2, 5,7, 9,6)

      #infer clonal evolution tree
      y = infer.clonal.models(variants = dat,
        cluster.col.name ='cluster',
        vaf.col.names = vafs_cols,
        cancer.initiation.model='monoclonal',
        #subclonal.test = 'none',
        subclonal.test ='bootstrap',
        subclonal.test.model ='non-parametric',
        #subclonal.test.model ='non-parametric',
        #num.boots = 1000,
        ignore.clusters=c(2, 5,7, 9,6),
        score.model.by = 'metap',
        seeding.aware.tree.pruning = TRUE,
        cluster.center ='mean',
        min.cluster.vaf = 0,
          founding.cluster = 1,
          clone.colors = col_vector)
    }

    if(patient == "LY_RAP_0002"){
      z1 = which(dat$cluster == 1)
      z2 = which(dat$cluster == 3)
      dat$cluster[z2]=1
      dat$cluster[z1]=3

      #make all clonal clusters = 100% CP
      dat[which(dat$cluster==1), 4:7] = 50
      dat[which(dat$cluster==10)]$Adrenal_gland_NOS = 37
      dat[which(dat$cluster==4)]$Adrenal_gland_NOS = 0
      dat[which(dat$cluster==4)]$Liver_Left_lobe = 0

      dat[which(dat$cluster==12)]$Adrenal_gland_NOS = 0
      dat[which(dat$cluster==12)]$Liver_Left_lobe = 0

      dat[which(dat$cluster==5)]$Adrenal_gland_NOS = 0
      dat[which(dat$cluster==5)]$Thorax_NOS = 0

      dat[which(dat$cluster==9)]$Liver_Left_lobe = 0
      dat[which(dat$cluster==9)]$Mesenteric_lymph_node_NOS = 0

      dat[which(dat$cluster==10)]$Liver_Left_lobe = 0
      dat[which(dat$cluster==10)]$Mesenteric_lymph_node_NOS = 0
      dat[which(dat$cluster==10)]$Thorax_NOS = 0

      dat[which(dat$cluster==13)]$Liver_Left_lobe = 0

      clusters_remove=c(8, 2, 6, 11, 7,3)

      #infer clonal evolution tree
      y = infer.clonal.models(variants = dat,
        cluster.col.name ='cluster',
      vaf.col.names = vafs_cols,
      cancer.initiation.model='monoclonal',
      #subclonal.test ='none',
      #subclonal.test = 'bootstrap',
      #subclonal.test.model ='non-parametric',
      ignore.clusters=c(8, 2, 6, 11, 7,3),
      #score.model.by = 'metap',
      #seeding.aware.tree.pruning = TRUE,
      cluster.center ='mean',
      min.cluster.vaf = 0.001,
        founding.cluster = 1,
        clone.colors = col_vector)
    }

    if(patient == "LY_RAP_0003"){
      z1 = which(dat$cluster == 1)
      z2 = which(dat$cluster == 5)
      dat$cluster[z2]=1
      dat$cluster[z1]=5

      #make all clonal clusters = 100% CP
      dat[which(dat$cluster==1), 4:23] = 50

      dat[which(dat$cluster==2)]$Spleen = 49
      dat[which(dat$cluster==9)]$Abdomen_NOS = 48
      dat[which(dat$cluster==9)]$Inguinal_region_NOS = 48
      dat[which(dat$cluster==5)]$Axilla_NOS = 48
      dat[which(dat$cluster==11)]$Abdomen_NOS = 47.5

      dat[which(dat$cluster==11)]$Axilla_NOS = 0
      dat[which(dat$cluster==11)]$Kidney_NOS = 0
      dat[which(dat$cluster==11)]$left_breast = 0
      dat[which(dat$cluster==11)]$Mediastinum_NOS = 0
      dat[which(dat$cluster==11)]$Omentum = 0
      dat[which(dat$cluster==11)]$right_neck_LN = 0
      dat[which(dat$cluster==11)]$Shoulder_NOS = 0
      dat[which(dat$cluster==11)]$Spleen = 0

      dat[which(dat$cluster==10)]$Bladder_NOS = 0
      dat[which(dat$cluster==10)]$left_axilla_LN = 0
      dat[which(dat$cluster==10)]$left_breast = 0
      dat[which(dat$cluster==10)]$Mediastinum_NOS = 0
      dat[which(dat$cluster==10)]$Omentum = 0
      dat[which(dat$cluster==10)]$Shoulder_NOS = 0
      dat[which(dat$cluster==10)]$Pancreas_NOS = 0
      dat[which(dat$cluster==10)]$Retroperitoneum_NOS = 0

      clusters_remove=c(2, 5,7, 9,6)

      #infer clonal evolution tree
      y = infer.clonal.models(variants = dat,
        cluster.col.name ='cluster',
      vaf.col.names = vafs_cols,
      cancer.initiation.model='monoclonal',
      #subclonal.test ='none',
      #subclonal.test = 'bootstrap',
      #subclonal.test.model ='non-parametric',
      ignore.clusters=c(3, 6, 12, 8, 4),
      #score.model.by = 'metap',
      #seeding.aware.tree.pruning = TRUE,
      cluster.center ='mean',
      min.cluster.vaf = 0.001,
        founding.cluster = 1,
        clone.colors = col_vector)
    }

    #y <-transfer.events.to.consensus.trees(y,dat[dat$is.driver,],
    #  cluster.col.name ='cluster',event.col.name ='symbol')

    y <-convert.consensus.tree.clone.to.branch(y, branch.scale ='sqrt')

    pdf(paste(patient, 'all_trees.pdf', sep="_"), width = 3, height = 5, useDingbats = FALSE)
    plot.all.trees.clone.as.branch(y)
    dev.off()

    plot.clonal.models(y,
      # box plot parameters
      box.plot = TRUE,
      #fancy.boxplot = TRUE,
      #fancy.variant.boxplot.highlight ='is.driver',
      #fancy.variant.boxplot.highlight.shape = 21,
      #fancy.variant.boxplot.highlight.fill.color ='red',
      fancy.variant.boxplot.highlight.color ='black',
      #fancy.variant.boxplot.highlight.note.col.name ='symbol',
      fancy.variant.boxplot.highlight.note.color ='blue',
      fancy.variant.boxplot.highlight.note.size = 1,
    fancy.variant.boxplot.jitter.alpha = 1, fancy.variant.boxplot.jitter.center.color ='grey50',
    fancy.variant.boxplot.base_size = 5, fancy.variant.boxplot.plot.margin = 1,
    fancy.variant.boxplot.vaf.suffix ='.VAF',
    # bell plot parameters
    clone.shape ='bell',bell.event = TRUE, bell.event.label.color ='blue',
    bell.event.label.angle = 60, clone.time.step.scale = 1, bell.curve.step = 2,
    # node-based consensus tree parameters
    merged.tree.plot = TRUE,tree.node.label.split.character = NULL,
    tree.node.shape ='circle',tree.node.size = 20,tree.node.text.size = 0.5,
    merged.tree.node.size.scale = 1.25,merged.tree.node.text.size.scale = 2.5,
    merged.tree.cell.frac.ci = FALSE,
    # branch-based consensus tree parameters
    merged.tree.clone.as.branch = TRUE,mtcab.event.sep.char =',',
    mtcab.branch.text.size = 1,
    mtcab.branch.width = 0.75,mtcab.node.size = 2,mtcab.node.label.size = 1,
    mtcab.node.text.size = 1.5,
    # cellular population parameters
    cell.plot = TRUE,num.cells = 100,cell.border.size = 0.25,
    cell.border.color ='black',clone.grouping ='horizontal',
    #meta-parameters
    scale.monoclonal.cell.frac = TRUE,show.score = FALSE,cell.frac.ci = TRUE,
    disable.cell.frac = FALSE,
    # output figure parameters
    out.dir = paste(patient, 'all_output', sep="_"),out.format ='pdf',overwrite.output = TRUE,
    width = 40,height = 30)

    #mut info
    mut_info = merge(mut_gene, dat, by=c("mut_id", "symbol"))
    mut_info$cluster_removed=""
    z = which(mut_info$cluster %in% clusters_remove)
    mut_info$cluster_removed[z] = "removed"
    library(openxlsx)
    write.xlsx(mut_info, paste(patient, "all_mutations", 'Pyclone-VI-clonevol-results.xlsx', sep="_"))

    #save input data required for mapscape
    #adjacency matrix
    #make manually for now

    #cp values mean per cluster
    mean_cps = melt(dat, id.vars = c("cluster", "cluster_id", "mut_id", "symbol", "is.driver")) %>%
    select(cluster,variable, value)

    mean_cps = as.data.table(mean_cps %>% group_by(variable, cluster) %>%
    dplyr::summarize(mean_cp=mean(value)))

    #convert back from VAF to CCF
    mean_cps$mean_cp = mean_cps$mean * 2 / 100
    colnames(mean_cps) = c("sample_id" ,"clone_id", "clonal_prev")
    write.table(mean_cps, file=paste(date, patient, "all_mutations", "_clonevol_output_for_mapscape.txt", sep=""), quote=F, row.names=F, sep="\t")

    #make quick and easy heatmap of all clusters
    mean_cps = dcast(mean_cps, sample_id ~ clone_id,
        value.var = "clonal_prev")
    rownames(mean_cps) = mean_cps$sample_id
    mean_cps$sample_id = NULL
    mean_cps = as.matrix(mean_cps)
    library("viridis")           # Load
    pdf(paste(patient, 'all_clusters_CP_heatmap.pdf', sep="_"))
    heatmap.2(mean_cps, scale = "none", col=brewer.pal(n = 9, name = "YlOrRd"),
          trace = "none", density.info = "none", cexRow=1)
    dev.off()

}#end function patient input

p001_dat = get_patient_pyclone_plot("LY_RAP_0001")
p002_dat = get_patient_pyclone_plot("LY_RAP_0002")
p003_dat = get_patient_pyclone_plot("LY_RAP_0003")

#to make tree need to have founding clone be labelled 1
#so remove the first cluster since ignoring it anyways

#-----
#DONE-
#-----
