#----------------------------------------------------------------------

#----------------------------------------------------------------------

#----------------------------------------------------------------------
#load functions and libraries
#----------------------------------------------------------------------

options(stringsAsFactors=F)

#load libraries
packages <- c("dplyr", "readr", "ggplot2", "vcfR", "tidyr", "mclust", "data.table",
              "plyr",
              "ggrepel", "stringr", "maftools", "magrittr", "ggExtra", "cowplot")
lapply(packages, require, character.only = TRUE)
library("readxl")

date = Sys.Date()

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#using output data tables from pyclone
#let's plot VAfs of T1 versus T2
#these output files were generated using the script --> pyclone_run_analysis.sh

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#CNAs annotated by gene that they overlap (no SNVs)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/TITAN_CNA/results/titan/hmm/optimalClusterSolution_files/titanCNA_ploidy2")
cnas_all = fread(list.files(pattern="all_CNAs_protein_coding_samples.txt")[length(list.files(pattern="all_CNAs_protein_coding_samples.txt"))])

setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/merged_MUTECT2_STRELKA/merged_variants_vcfs/vcf_summary_text")

#sample info
samps = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/RAP_samples_information.txt")

#DLBCL driver genes from Reddy et al 2017
reddy = as.data.table(read_excel("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/Reddyetal_2017_driver_mutations.xlsx"))

#DLBCL mutations from Morin Blood 2013
morin = as.data.table(read_excel("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/supp_blood-2013-02-483727_TableS3.xlsx"))
genes_sum=as.data.table(table(morin$Gene))
genes_sum = as.data.table(filter(genes_sum, N > 5))
colnames(genes_sum)=c("Gene", "num_samples_w_mut")

#Our mutations
#muts = fread(list.files(pattern="all_SNVs_samples.txt")[length(list.files(pattern="all_SNVs_samples.txt"))])
read_only = fread(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.txt")[length(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.txt"))])

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
files = list.files(pattern="table_file.txt")
files ="Pyclone_July2020_table_file.txt"

#data - table generated by pyclone (cluster)
files_cluster = list.files(pattern="cluster.txt")
files_cluster="Pyclone_July2020_table_file_cluster.txt"

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

pyclone_file= fread(files)

#how many mutations in each cluster?
cluster_sum = unique(pyclone_file[,c("cluster_id", "mutation_id")])

cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=2)

#let's keep only the clusters with more than two mutations in them
pyclone_file = filter(pyclone_file, cluster_id %in% cluster$V1)

muts = dcast(pyclone_file, cluster_id + mutation_id ~ sample_id, value.var = "cellular_prevalence")
clusters = muts[,c(1:2)]

#mutation file
muts_final = muts[,3:ncol(muts)]
file = paste(date, "rap_citup_input_freqs.txt", sep="_")
write.table(muts_final, file, quote=F, row.names=F, col.names=F, sep="\t")

#cluster file
clusters = muts[,c("cluster_id")]
file = paste(date, "rap_citup_input_clusters.txt", sep="_")
write.table(clusters, file, quote=F, row.names=F, col.names=F, sep="\t")

#get melted version of matrix
melted_muts= as.data.table(melt(muts, id=c("mutation_id", "cluster_id")))

#for each cluster and sample get mean cell prev
mean_cp_clusters = as.data.table(melted_muts %>% group_by(cluster_id, variable) %>%
dplyr::summarize(mean_cp=mean(value)))

#summarize for each patient their mean cellular prev for each cluster
#first summarize per cluster each sample's cellular prevalence
mean_cp_clusters$variable = as.character(mean_cp_clusters$variable)
mean_cp_clusters$sample_name = sapply(mean_cp_clusters$variable,
function(x){unlist(strsplit(x, "_pyclone_input"))[1]})

mean_cp_clusters$cluster_id = factor(mean_cp_clusters$cluster_id)

pdf("summary_short_list_pyclone_cell_prev.pdf", width=15)
p<-ggplot(mean_cp_clusters, aes(x=cluster_id, y=mean_cp, group=sample_name)) +
  geom_line(aes(color=sample_name))+
  geom_point(aes(color=sample_name))

p <- p + theme_minimal()
p + theme(legend.position="bottom")+ theme(legend.text=element_text(size=4))
dev.off()

#add mutation info
melted_muts$variable = as.character(melted_muts$variable)
melted_muts$id = sapply(melted_muts$variable,
function(x){unlist(strsplit(x, "_pyclone_input"))[1]})
colnames(melted_muts)[1] = "mut_id"

muts_info = as.data.table(unique(read_only[,c("mut_id",
"symbol", "ExonicFunc.ensGene", "Func.ensGene", "AAChange.ensGene")]))

melted_muts = merge(melted_muts, muts_info, by=c("mut_id"))

#plot for each pair of samples cell prev for each mutation
get_prev_plot = function(sample, samples_all){
  #remaining samples to compare to
  samples_all = samples_all[which(!(samples_all == sample))]
  for(i in 1:length(samples_all)){
    samp = samples_all[i]
    z = which(colnames(muts) %in% c(samp, sample, "cluster_id"))
    dat = muts[,..z]
    xlab = colnames(dat)[2]
    ylab = colnames(dat)[3]
    colnames(dat)[2:3]=c("sample1", "sample2")
    dat$cluster_id = as.factor(dat$cluster_id)
    #make plot
    sp <- ggplot(dat, aes(x=sample1, y=sample2, color=cluster_id)) +
    geom_point() + theme_classic() +
     geom_hline(yintercept=0.5, linetype="dashed", color = "grey")+
      geom_vline(xintercept=0.5, linetype="dashed", color = "grey")
    sp = sp + geom_density_2d() +xlab(xlab) + ylab(ylab)
    print(sp)
  }
  print("done sample")
}

samples = colnames(muts)[3:ncol(muts)]
pdf(paste(date, "pyclone_cell_prev_across_samples.pdf", sep="_"))
llply(samples, get_prev_plot, samples)
dev.off()



#-----
#DONE-
#-----
