#-------------------------------------------------------------------------------
#pyclone-vi_005_pyclone_mutation_signatures_in_clusters.R
#Karin Isaev
#March 3rd 2021, 2021
#load R/4.0.0
#-------------------------------------------------------------------------------

#load packages and data
source("/cluster/home/kisaev/RAP_WGS/config-file.R")
library("gplots")
#library(MutationalPatterns)
library(BSgenome)
ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)
library(NMF)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(biomaRt)
library(GenomicRanges)
library(maftools)
#Requires BSgenome object
library(BSgenome.Hsapiens.UCSC.hg19, quietly = TRUE)
#library(logr)
library('pheatmap')

library(dplyr)
library(reshape2)
#library(kableExtra)
library(ggplot2)
library(gridExtra)
library(BSgenome.Hsapiens.UCSC.hg19)
hg19 <- BSgenome.Hsapiens.UCSC.hg19
library(ggpubr)

# Load mutSignatures
#library(mutSignatures)
library(MutationalPatterns)

ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#set up patients
patients= c("LY_RAP_0001", "LY_RAP_0002", "LY_RAP_0003")

#test
#patient = "LY_RAP_0003"

z = which(read_only$Tissue_Site == "Aorta, ascending, not specified \n\n")
if(!(length(z) == 0)){
read_only$Tissue_Site[z] = "Aorta, ascending"}

#pyclone input files
p001_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0001_pyclone_input.tsv")
p002_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0002_pyclone_input.tsv")
p003_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0003_pyclone_input.tsv")

#pyclone output files
p001_pyclone_output = fread("10-06-2021/all_samples_pyclonevi_LY_RAP_0001_beta-binomial_rap_wgs_all_muts.tsv")
p002_pyclone_output = fread("10-06-2021/all_samples_pyclonevi_LY_RAP_0002_beta-binomial_rap_wgs_all_muts.tsv")
p003_pyclone_output = fread("10-06-2021/all_samples_pyclonevi_LY_RAP_0003_beta-binomial_rap_wgs_all_muts.tsv")

#pairtree clusters - files made manually
p001_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-11_input_files/results2/p001_pairtree_clones.txt")
p002_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-11_input_files/results2/p002_pairtree_clones.txt")
p003_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-11_input_files/results2/p003_pairtree_clones.txt")

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#use pyclone results clusters to identify mutation signatures associated
#with different clones

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

get_mut_signatures = function(patient, pyclone_output, pairtree_cluster){

  #read in mutation data for each cluster as obtained from pyclone
  muts <- pyclone_output

  #get clusters
  clusters = unique(muts$cluster_id)

  #make folder to store plots for patient
  mainDir <- "/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone/clusters_mutation_signatures"
  subDir <- patient

  dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
  setwd(file.path(mainDir, subDir))

  #for each cluster gather mutations and their details from main mutation
  #file

  cluster_muts = unique(muts[,c("mutation_id", "cluster_id")])

  t = as.data.table(table(cluster_muts$cluster_id))
  t = filter(t, N >30)
  muts_keep = filter(cluster_muts, cluster_id %in% t$V1)
  colnames(t)= c("cluster_id", "num_muts")

  if(patient == "LY_RAP_0003"){
    t$num_muts[t$cluster_id == 4] = 93
  }

  t=merge(t, pairtree_cluster)
  colnames(t)[3] = "pairtree_cluster_name"
  t$cluster_id = as.numeric(t$cluster_id)

  muts_keep = merge(muts_keep, t, by="cluster_id")

  mut.merged = as.data.table(filter(read_only, STUDY_PATIENT_ID == patient, mut_id %in% cluster_muts$mutation_id))
  mut.merged = unique(mut.merged[,c("mut_id", "ensgene", "POS", "CHROM", "symbol", "REF","ALT",
  "Gene.ensGene", "GeneDetail.ensGene", "ExonicFunc.ensGene", "Func.ensGene", "cosmic68")])
  mut.merged$Variant_Classification = paste(mut.merged$Func.ensGene, mut.merged$ExonicFunc.ensGene)
  colnames(mut.merged)[1] = "mutation_id"

  mut.merged = merge(muts_keep, mut.merged, by="mutation_id")

  colnames(mut.merged)[6] = "start"
  mut.merged$end = mut.merged$start
  colnames(mut.merged)[7] = "chr"
  colnames(mut.merged)[8] = "Hugo_Symbol"
  mut.merged$Tumor_Sample_Barcode = patient

  #how many cosmic mutations across clones
  cos = as.data.table(table(mut.merged$pairtree_cluster_name, mut.merged$cosmic68))
  cos = as.data.table(table(mut.merged$pairtree_cluster_name, mut.merged$cosmic68, mut.merged$Hugo_Symbol)) %>% filter(N >0, !(V2 == "."))
  cos_sum = as.data.table(table(cos$V1))
  colnames(cos_sum) = c("Pairtree_cluster", "Number_cosmic_mutations")

  pdf("cosmic_muts_across_clones.pdf", width=4, height=6)
  g = ggbarplot(cos_sum, x = "Pairtree_cluster", y="Number_cosmic_mutations")+
  xlab("Pairtree Clone") + ylab("# of COSMIC mutations")+theme_classic()+
  theme(axis.text = element_text(size = 12, color="black"))
  print(g)
  dev.off()
  print(cos)
  print("pass")

  #which driver gene mutations in which clones
  mut.merged$driver = ""
  z1 = which(mut.merged$Hugo_Symbol %in% all_drivers$Gene[all_drivers$patient == patient])
  z2 = which((mut.merged$Func.ensGene %in% c("exonic", "splicing", "exonic\\x3bsplicing")) &
  (mut.merged$ExonicFunc.ensGene %in% c("nonsynonymous_SNV", "stopgain",
  "frameshift_deletion", "frameshift_insertion", "stoploss", ".")))
  z = z2[which(z2 %in% z1)]
  mut.merged$driver[z] = "driver"
  mut.merged$cosmic[!(mut.merged$cosmic68 == ".")] = "cosmic"
  mut.merged = unique(mut.merged[,c("pairtree_cluster_name", "Hugo_Symbol", "driver", "cosmic")]) %>%
      filter(!(driver=="") | !(cosmic=="."))
  missing_clones = t$pairtree_cluster_name[which(!(t$pairtree_cluster_name %in% mut.merged$pairtree_cluster_name))]
  add_clones = as.data.frame(matrix(nrow=length(missing_clones), ncol=4))
  colnames(add_clones) = colnames(mut.merged)
  add_clones$pairtree_cluster_name = missing_clones
  mut.merged = rbind(mut.merged, add_clones)
  mut.merged$Hugo_Symbol[is.na(mut.merged$Hugo_Symbol)] = mut.merged$Hugo_Symbol[!(is.na(mut.merged$Hugo_Symbol))][1]

  gg=as.data.table(table(mut.merged$pairtree_cluster_name, mut.merged$Hugo_Symbol))
  colnames(gg) = c("pairtree_cluster_name", "Hugo_Symbol", "num_muts_in_genes")
  gg$pairtree_cluster_name = as.numeric(gg$pairtree_cluster_name)

  mut.merged = merge(mut.merged, gg, by=c("pairtree_cluster_name", "Hugo_Symbol"))

  mut.merged = mut.merged[order(pairtree_cluster_name)]
  mut.merged$pairtree_cluster_name = factor(mut.merged$pairtree_cluster_name, levels=unique(mut.merged$pairtree_cluster_name))

  mut.merged$driver[mut.merged$driver == ""] = NA
  mut.merged$driver = factor(mut.merged$driver, levels=c("driver", NA))

  mut.merged$cosmic[mut.merged$cosmic == ""] = NA
  mut.merged$cosmic = factor(mut.merged$cosmic, levels=c("cosmic", NA))

  mut.merged$num_muts_in_genes[is.na(mut.merged$driver) & is.na(mut.merged$cosmic)] = ""

  genes_order = filter(mut.merged, !(num_muts_in_genes==""))
  genes_order = as.data.table(table(genes_order$Hugo_Symbol))
  genes_order = genes_order[order(-N)]
  mut.merged$Hugo_Symbol = factor(mut.merged$Hugo_Symbol, levels=genes_order$V1)

  pdf("cosmic_drivers_muts_across_clones.pdf", width=6, height=6)
  g = ggplot(mut.merged, aes(x=pairtree_cluster_name, y=Hugo_Symbol)) +
  theme_bw()+
  geom_tile(aes(fill=cosmic,width=0.75, height=0.75, color=driver),size=0.55) +
  geom_text(aes(label=num_muts_in_genes))+
     xlab("Pairtree clone")+
     scale_colour_manual(values = c("black", "grey"),
       na.value="transparent")+
       scale_fill_manual(values = c("orange", "white"),
       na.value="transparent")

  g= ggpar(g,legend ="bottom")
  print(g)
  dev.off()

  setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
  return(all_clusts)
}

p001 = get_mut_signatures("LY_RAP_0001", p001_pyclone_output, p001_pairtree)
p002 = get_mut_signatures("LY_RAP_0002", p002_pyclone_output, p002_pairtree)
p003 = get_mut_signatures("LY_RAP_0003", p003_pyclone_output, p003_pairtree)

#-----
#DONE-
#-----
