#----------------------------------------------------------------------
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#load functions and libraries
#----------------------------------------------------------------------

options(stringsAsFactors=F)

#load libraries
packages <- c("dplyr", "readr", "ggplot2", "vcfR", "tidyr", "mclust", "data.table",
              "plyr", "clonevol", "readxl", "pheatmap",
              "ggrepel", "stringr", "maftools", "magrittr", "ggExtra", "cowplot")
lapply(packages, require, character.only = TRUE)

date = Sys.Date()
library(MutationalPatterns)
lapply(packages, require, character.only = TRUE)
library(VariantAnnotation)
library(MutationalPatterns)
library(BSgenome)
ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)
library(NMF)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(biomaRt)
library(GenomicRanges)

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#use pyclone clustering results from small subset of mutations to
#generate tree

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#Our mutations
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/merged_MUTECT2_STRELKA/merged_variants_vcfs/vcf_summary_text")
read_only = readRDS(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.rds")[length(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.rds"))])

setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#sample info
samps = readRDS("/cluster/projects/kridelgroup/RAP_ANALYSIS/copy_RAP_masterlist_samples.rds")
colnames(samps)[4] ="Indiv"
z = which(samps$Indiv %in% read_only$Indiv)
samps = samps[z,]
samps[18,2] = "Kidney, NOS 2"

read_only$Tissue_Site = NULL
read_only$STUDY_PATIENT_ID = NULL
read_only$Specimen_Type = NULL

read_only = merge(read_only, samps, by = "Indiv")

#DLBCL driver genes from Reddy et al 2017
reddy = as.data.table(read_excel("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/Reddyetal_2017_driver_mutations.xlsx"))

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#results from pyclone-vi
patients= c("LY_RAP_0001", "LY_RAP_0002", "LY_RAP_0003")

test="LY_RAP_0002_all_mutations_Pyclone-VI-clonevol-results.xlsx"

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

get_mut_signatures = function(patient_clonevol_results){

  #read in mutation data for each cluster as obtained from pyclone
  muts <- as.data.table(read_excel(patient_clonevol_results))

  #prepare for mutation signature analysis


}








#-----
#DONE-
#-----
