#----------------------------------------------------------------------
#pyclone_008_make_cloneevol_input.R
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#load functions and libraries
#----------------------------------------------------------------------

options(stringsAsFactors=F)

#load libraries
packages <- c("dplyr", "readr", "ggplot2", "vcfR", "tidyr", "mclust", "data.table",
              "plyr", "clonevol", "readxl", "pheatmap",
              "ggrepel", "stringr", "maftools", "magrittr", "ggExtra", "cowplot")
lapply(packages, require, character.only = TRUE)

date = Sys.Date()

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#use pyclone clustering results from small subset of mutations to
#generate tree

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#Our mutations
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/merged_MUTECT2_STRELKA/merged_variants_vcfs/vcf_summary_text")
read_only = fread(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.txt")[length(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.txt"))])

setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
#sample info
samps = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/RAP_samples_information.txt")

#DLBCL driver genes from Reddy et al 2017
reddy = as.data.table(read_excel("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/Reddyetal_2017_driver_mutations.xlsx"))

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
files = list.files(pattern="table_file.txt")
files ="Pyclone_subset_muts_Sept2020_table_file.txt"

#data - table generated by pyclone (cluster)
files_cluster = list.files(pattern="cluster.txt")
files_cluster="Pyclone_subset_muts_Sept2020_table_file_cluster.txt"

#results from pyclone-vi
vi=fread("rap_wgs_subset_muts.tsv")

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

#summary of mutation data
mut_gene = unique(read_only[,c("mut_id", "symbol", "biotype", "Func.ensGene", "ExonicFunc.ensGene",
"AAChange.ensGene", "cosmic68")])

#pyclone_file= fread(files)
pyclone_file=vi

#remove clusters with low cluster_assignment_prob
pyclone_remove = unique(as.data.table(filter(pyclone_file, cluster_assignment_prob < 0.5, is.na(cellular_prevalence_std)))$cluster_id)

#how many mutations in each cluster?
cluster_sum = unique(pyclone_file[,c("cluster_id", "mutation_id")])

cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=2)

#let's keep only the clusters with more than five mutations in them
pyclone_file = filter(pyclone_file, cluster_id %in% cluster$V1, !(cluster_id %in% pyclone_remove))
colnames(pyclone_file)[1] = "mut_id"
pyclone_file_merged = merge(pyclone_file, mut_gene, by="mut_id")

#ClonEvol requires an input data frame consisting of at least a
#cluster column and one or more variant cellular prevalence columns,
#each corresponds to a sample.
samps = as.data.frame(unique(pyclone_file_merged$sample_id))
colnames(samps)[1] = "sample_id"
samps$sample = ""
samps$sample = c(
"FFPE_left_axilla_LN",
"FFPE_left_breast",
"FFPE_right_neck_LN",
"FT_Abdomen",
"FT_Adrenal_gland",
"FT_Axilla",
"FT_Bladder",
"FT_Cecum",
"FT_Cervical_lymph_node",
"FT_Inguinal_region",
"FT_Kidney_NOS_341360",
"FT_Kidney_NOS_341364",
"FT_Mediastinum",
"FT_Omentum",
"FT_Pancreas",
"FT_Parotid_gland",
"FT_Retroperitoneum",
"FT_Shoulder",
"FT_Spleen",
"FT_Stomach")

pyclone_file_merged = merge(pyclone_file_merged, samps, by="sample_id")
pyclone_file_merged$vaf_fixed = pyclone_file_merged$cellular_prevalence /2 *100

summaries_vafs_fixed = as.data.table(pyclone_file_merged %>%
  group_by(sample, cluster_id) %>%
  dplyr::summarize(mean=mean(cellular_prevalence)))

summaries_vafs_fixed = dcast(summaries_vafs_fixed, sample ~ cluster_id,
  value.var = "mean")

rownames(summaries_vafs_fixed) = summaries_vafs_fixed$sample
summaries_vafs_fixed$sample = NULL
summaries_vafs_fixed = as.matrix(summaries_vafs_fixed)
col<- colorRampPalette(c("red", "white", "blue"))(256)
pdf("heatmap_clusters_summary.pdf", width=10, height=10)
pheatmap(summaries_vafs_fixed, cutree_cols=3)
dev.off()

input = dcast(pyclone_file_merged, mut_id + symbol + cluster_id ~ sample,
  value.var = "vaf_fixed")
input$is.driver = ""
z = which(input$symbol %in% reddy$Gene)
input$is.driver[z] = TRUE
input$is.driver[-z] = FALSE

#> head(x)
#    cluster  gene is.driver P.vaf R.vaf  P.ccf R.ccf P.ref.count P.var.count
#226       1  SMC3      TRUE 50.28 49.13 100.56 98.26        3027        2611
#349       1 PTPRT      TRUE 45.24 45.31  90.48 90.62        2159        1799
#1         1     -     FALSE 43.83 41.37  87.66 82.74        2931        2364
#2         1     -     FALSE 41.23 46.47  82.46 92.94        2203        1658
#3         1     -     FALSE 48.91 43.11  97.82 86.22        2534        2358
#4         1     -     FALSE 47.54 44.45  95.08 88.90        2539        2271
#    P.depth R.ref.count R.var.count R.depth     P     R
#226    5639        2035        1990    4024 50.28 49.13
#349    3958        1715        1579    3294 45.24 45.31
#1      5296        2224        1501    3725 43.83 41.37
#2      3862        1733        1587    3320 41.23 46.47
#3      4893        2605        1873    4479 48.91 43.11
#4      4810        2325        2041    4366 47.54 44.45

input$cluster_id = as.numeric(input$cluster_id)
input = input[order(cluster_id)]
clusts = as.data.frame(unique(input$cluster_id)) ; colnames(clusts)="cluster_id"
clusts$cluster = 1:nrow(clusts)
input = merge(input, clusts, by = "cluster_id")
dat=input
dat$cluster = as.character(dat$cluster)

#visualizing clusters

library(RColorBrewer)
n <- 20
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

dat$is.driver = as.logical(dat$is.driver)

pdf('box.pdf', width = 9, height = 20, useDingbats = FALSE, title='')

pp <-plot.variant.clusters(dat,
  cluster.col.name ='cluster',
show.cluster.size = TRUE,
cluster.size.text.color ='blue',
vaf.col.names = colnames(dat)[4:23],
vaf.limits = 75,
sample.title.size = 5,
violin = FALSE,
box = FALSE,
jitter = TRUE,
jitter.color = col_vector,
jitter.shape = 1,
highlight ='is.driver',
highlight.shape = 21,
highlight.color ='blue',
highlight.fill.color ='green',
highlight.note.col.name ='symbol',
highlight.note.size = 1,
jitter.size = 1,
jitter.alpha = 1,
jitter.center.method ='median',
jitter.center.size = 1,
jitter.center.color ='darkgray',
jitter.center.display.value ='none',
order.by.total.vaf = TRUE)

dev.off()

pdf('flow.pdf', width=20, height=10, useDingbats=FALSE, title='')
plot.cluster.flow(dat, vaf.col.names = colnames(dat)[4:23],
  colors = col_vector)
dev.off()

#infer clonal evolution tree
y = infer.clonal.models(variants = dat,
  cluster.col.name ='cluster',
vaf.col.names = colnames(dat)[5:6],
cancer.initiation.model='monoclonal',
#subclonal.test ='bootstrap',
subclonal.test = 'none',
num.boots = 1,
#ignore.clusters=c(6,8),
founding.cluster = 9,
#score.model.by = 'metap',
cluster.center ='mean', min.cluster.vaf = 0.01,
          sum.p = 0.01,
          seeding.aware.tree.pruning=FALSE,
          alpha = 0.001,
clone.colors = col_vector)

y <-transfer.events.to.consensus.trees(y,dat[dat$is.driver,],
  cluster.col.name ='cluster',event.col.name ='symbol')

y <-convert.consensus.tree.clone.to.branch(y, branch.scale ='sqrt')

pdf('trees.pdf', width = 3, height = 5, useDingbats = FALSE)
plot.all.trees.clone.as.branch(y, branch.width = 0.5,node.size = 1,
  node.label.size = 0.5)
dev.off()

plot.clonal.models(y,
  # box plot parameters
  box.plot = TRUE,fancy.boxplot = TRUE,
  fancy.variant.boxplot.highlight ='is.driver',
  fancy.variant.boxplot.highlight.shape = 21,
  fancy.variant.boxplot.highlight.fill.color ='red',
  fancy.variant.boxplot.highlight.color ='black',
  fancy.variant.boxplot.highlight.note.col.name ='symbol',
  fancy.variant.boxplot.highlight.note.color ='blue',
  fancy.variant.boxplot.highlight.note.size = 1,
fancy.variant.boxplot.jitter.alpha = 1, fancy.variant.boxplot.jitter.center.color ='grey50',
fancy.variant.boxplot.base_size = 5, fancy.variant.boxplot.plot.margin = 1,
fancy.variant.boxplot.vaf.suffix ='.VAF',
# bell plot parameters
clone.shape ='bell',bell.event = TRUE, bell.event.label.color ='blue',
bell.event.label.angle = 60, clone.time.step.scale = 1, bell.curve.step = 2,
# node-based consensus tree parameters
merged.tree.plot = TRUE,tree.node.label.split.character = NULL,
tree.node.shape ='circle',tree.node.size = 20,tree.node.text.size = 0.5,
merged.tree.node.size.scale = 1.25,merged.tree.node.text.size.scale = 2.5,
merged.tree.cell.frac.ci = FALSE,
# branch-based consensus tree parameters
merged.tree.clone.as.branch = TRUE,mtcab.event.sep.char =',',
mtcab.branch.text.size = 1,
mtcab.branch.width = 0.75,mtcab.node.size = 2,mtcab.node.label.size = 1,
mtcab.node.text.size = 1.5,
# cellular population parameters
cell.plot = TRUE,num.cells = 100,cell.border.size = 0.25,
cell.border.color ='black',clone.grouping ='horizontal',
#meta-parameters
scale.monoclonal.cell.frac = TRUE,show.score = FALSE,cell.frac.ci = TRUE,
disable.cell.frac = FALSE,
# output figure parameters
out.dir ='output',out.format ='pdf',overwrite.output = TRUE,
width = 20,height = 8,
# vector of width scales for each panel from left to right
panel.widths =c(3,4,2,4,2))

#-----
#DONE-
#-----
