#-------------------------------------------------------------------------------
#pyclone-vi_005_pyclone_mutation_signatures_in_clusters.R
#Karin Isaev
#March 3rd 2021, 2021
#load R/4.0.0
#-------------------------------------------------------------------------------

#load packages and data
source("/cluster/home/kisaev/RAP_WGS/config-file.R")
library("gplots")
#library(MutationalPatterns)
library(BSgenome)
ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)
library(NMF)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(biomaRt)
library(GenomicRanges)
library(maftools)
#Requires BSgenome object
library(BSgenome.Hsapiens.UCSC.hg19, quietly = TRUE)
#library(logr)
library('pheatmap')

library(dplyr)
library(reshape2)
#library(kableExtra)
library(ggplot2)
library(gridExtra)
library(BSgenome.Hsapiens.UCSC.hg19)
hg19 <- BSgenome.Hsapiens.UCSC.hg19
library(ggpubr)
library(rjson)

# Load mutSignatures
#library(mutSignatures)
library(MutationalPatterns)

ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#set up patients
patients= c("LY_RAP_0001", "LY_RAP_0002", "LY_RAP_0003")

#test
#patient = "LY_RAP_0003"

z = which(read_only$Tissue_Site == "Aorta, ascending, not specified \n\n")
if(!(length(z) == 0)){
read_only$Tissue_Site[z] = "Aorta, ascending"}

#pyclone input files
p001_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0001_pyclone_input.tsv")
p002_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0002_pyclone_input.tsv")
p003_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0003_pyclone_input.tsv")

#pyclone output files
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone/23-06-2021")
p001_pyclone_output = fread("all_samples_pyclonevi_LY_RAP_0001_beta-binomial_rap_wgs_all_muts.tsv")
p002_pyclone_output = fread("all_samples_pyclonevi_LY_RAP_0002_beta-binomial_rap_wgs_all_muts.tsv")
p003_pyclone_output = fread("all_samples_pyclonevi_LY_RAP_0003_beta-binomial_rap_wgs_all_muts.tsv")

#pairtree clusters - files made manually
p001_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p001_pairtree_clones.txt")
p002_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p002_pairtree_clones.txt")
p003_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p003_pairtree_clones.txt")

#pairtree results json files
p001_pairtree_json = fromJSON(file="/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p001_solution.json")
p002_pairtree_json = fromJSON(file="/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p002_solution.json")
p003_pairtree_json = fromJSON(file="/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p003_solution.json")

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#use pyclone results clusters to identify mutation signatures associated
#with different clones

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#test
patient=patients[2]
pyclone_output=p002_pyclone_output
pairtree_cluster=p002_pairtree
pairtree_results=p002_pairtree_json

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

get_mapscape_input = function(patient, pyclone_output, pairtree_cluster, pairtree_results){

  #read in mutation data for each cluster as obtained from pyclone
  muts <- pyclone_output

  #get clusters
  clusters = unique(muts$cluster_id)

  #make folder to store plots for patient
  mainDir <- "/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone/mapscape"
  subDir <- patient

  dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
  setwd(file.path(mainDir, subDir))

  #for each cluster gather mutations and their details from main mutation
  #file

  cluster_muts = unique(muts[,c("sample_id", "mutation_id", "cluster_id", "cellular_prevalence")])

  tt = unique(muts[,c("mutation_id", "cluster_id")])
  t = as.data.table(table(tt$cluster_id))
  t = filter(t, N >100)
  muts_keep = filter(cluster_muts, cluster_id %in% t$V1)
  colnames(t)= c("cluster_id", "num_muts")

  t=merge(t, pairtree_cluster)
  colnames(t)[3] = "pairtree_cluster_name"
  t$cluster_id = as.numeric(t$cluster_id)
  muts_keep = merge(muts_keep, t, by="cluster_id")

  #add info about pairtree clusters/prevalences
  samples = as.data.table(pairtree_results$samples)

  subclonefreq = as.data.table(pairtree_results$phi)
  subclonefreq$samples = samples$V1
  subclonefreq = melt(subclonefreq)
  colnames(subclonefreq)[3] = "pairtree_subclone_freq"
  subclonefreq$variable = as.character(subclonefreq$variable)
  subclonefreq$variable = sapply(subclonefreq$variable, function(x){as.numeric(unlist(strsplit(x, "V"))[2])})
  colnames(subclonefreq)[1:2] = c("sample_id", "pairtree_cluster_name")

  muts_keep = merge(muts_keep, subclonefreq, by=c("sample_id", "pairtree_cluster_name"))
  muts_keep = unique(muts_keep[,c("sample_id", "pairtree_cluster_name", "pairtree_subclone_freq")])
  colnames(muts_keep) = c("sample_id", "clone_id", "clonal_prev")

  muts_keep$clone_id = as.numeric(muts_keep$clone_id)
  muts_keep$clonal_prev = as.numeric(muts_keep$clonal_prev)

  write.table(muts_keep, file="mapscape_input_from_pairtree_pyclonevi.txt", quote=F, row.names=F, sep="\t")

  setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
  print("done")
}

get_mapscape_input("LY_RAP_0001", p001_pyclone_output, p001_pairtree, p001_pairtree_json)
get_mapscape_input("LY_RAP_0002", p002_pyclone_output, p002_pairtree, p002_pairtree_json)
get_mapscape_input("LY_RAP_0003", p003_pyclone_output, p003_pairtree, p003_pairtree_json)

#-----
#DONE-
#-----
