#----------------------------------------------------------------------

#----------------------------------------------------------------------

#----------------------------------------------------------------------
#load functions and libraries
#----------------------------------------------------------------------

options(stringsAsFactors=F)
date = Sys.Date()

#load libraries
packages <- c("dplyr", "readr", "ggplot2", "vcfR", "tidyr", "mclust", "data.table",
              "plyr", "readxl",
              "ggrepel", "stringr", "maftools", "magrittr", "ggExtra", "cowplot")
lapply(packages, require, character.only = TRUE)

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#using output data tables from pyclone
#let's plot VAfs of T1 versus T2
#these output files were generated using the script --> pyclone_run_analysis.sh

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#CNAs annotated by gene that they overlap (no SNVs)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/TITAN_CNA/results/titan/hmm/optimalClusterSolution_files/titanCNA_ploidy2")
cnas_all = fread(list.files(pattern="all_CNAs_protein_coding_samples.txt")[length(list.files(pattern="all_CNAs_protein_coding_samples.txt"))])

setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/merged_MUTECT2_STRELKA/merged_variants_vcfs/vcf_summary_text")
#Our mutations
read_only = fread(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.txt")[length(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.txt"))])

#sample info
samps = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/RAP_samples_information.txt")

#DLBCL driver genes from Reddy et al 2017
reddy = as.data.table(read_excel("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/Reddyetal_2017_driver_mutations.xlsx"))

#DLBCL mutations from Morin Blood 2013
morin = as.data.table(read_excel("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/supp_blood-2013-02-483727_TableS3.xlsx"))
genes_sum=as.data.table(table(morin$Gene))
genes_sum = as.data.table(filter(genes_sum, N > 5))
colnames(genes_sum)=c("Gene", "num_samples_w_mut")

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
files = list.files(pattern="table_file.txt")
files ="Pyclone_subset_muts_Sept2020_table_file.txt"

#data - table generated by pyclone (cluster)
files_cluster = list.files(pattern="cluster.txt")
files_cluster="Pyclone_subset_muts_Sept2020_table_file_cluster.txt"

vi=fread("rap_wgs_all_muts_neut.tsv")

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

#summary of mutation data
mut_gene = unique(read_only[,c("mut_id", "symbol", "biotype", "Func.ensGene", "ExonicFunc.ensGene",
"AAChange.ensGene", "cosmic68")])

pyclone_file = vi

#read in main pyclone table result
#pyclone_file= fread(files)
pyclone_remove = unique(as.data.table(filter(pyclone_file, (cluster_assignment_prob < 0.5) | (is.na(cellular_prevalence_std))))$cluster_id)

#how many mutations in each cluster?
cluster_sum = unique(pyclone_file[,c("cluster_id", "mutation_id")])

cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=5)

#let's keep only the clusters with more than five mutations in them
pyclone_file = filter(pyclone_file, cluster_id %in% cluster$V1, !(cluster_id %in% pyclone_remove))
colnames(pyclone_file)[1] = "mut_id"
pyclone_file_merged = merge(pyclone_file, mut_gene, by="mut_id")
pyclone_file_merged = pyclone_file_merged[order(-cellular_prevalence)]

  #for each cluster and sample get mean cell prev
  mean_cp_clusters = as.data.table(pyclone_file_merged %>% group_by(sample_id, cluster_id) %>%
  dplyr::summarize(mean_cp=mean(cellular_prevalence)))
  mean_cp_clusters$cluster_id = factor(mean_cp_clusters$cluster_id)
  mean_cp_clusters$sample_name = sapply(mean_cp_clusters$sample_id,
  function(x){unlist(strsplit(x, "_subset_muts_pyclone_input"))[1]})
mean_cp_clusters = mean_cp_clusters[order(-mean_cp)]
mean_cp_clusters$cluster_id = factor(mean_cp_clusters$cluster_id, levels=unique(mean_cp_clusters$cluster_id))

pdf("summary_short_list_pyclone_cell_prev.pdf", width=10, height=6)

p = ggplot(mean_cp_clusters, aes(x=cluster_id, y=mean_cp, group=sample_name)) +
  geom_line(aes(color=sample_name))+
  geom_point(aes(color=sample_name))
p = p + theme_minimal()
p = p + theme(legend.position="bottom")+ theme(legend.text=element_text(size=4))
print(p)
dev.off()

#geom tile
pdf("summary_short_list_pyclone_cell_prev_tiles.pdf", width=9, height=6)
g = ggplot(mean_cp_clusters, aes(x=cluster_id, y=sample_name)) +
geom_tile(aes(fill=mean_cp,width=0.75, height=0.75),size=0.55, colour = "black")+
scale_fill_gradient(low = "grey", high = "purple", na.value = 'white')
print(g)
dev.off()

#-----
#DONE-
#-----
