#----------------------------------------------------------------------
#pyclone_005_make_citup.R
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#load functions and libraries
#----------------------------------------------------------------------

options(stringsAsFactors=F)

#load libraries
packages <- c("dplyr", "readr", "ggplot2", "vcfR", "tidyr", "mclust", "data.table",
              "plyr",
              "ggrepel", "stringr", "maftools", "magrittr", "ggExtra", "cowplot")
lapply(packages, require, character.only = TRUE)
library("readxl")

date = Sys.Date()

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#using output data tables from pyclone
#let's plot VAfs of T1 versus T2
#these output files were generated using the script --> pyclone_run_analysis.sh

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#Our mutations
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/merged_MUTECT2_STRELKA/merged_variants_vcfs/vcf_summary_text")
read_only = fread(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.txt")[length(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.txt"))])

setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
#sample info
samps = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/RAP_samples_information.txt")

#DLBCL driver genes from Reddy et al 2017
reddy = as.data.table(read_excel("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/Reddyetal_2017_driver_mutations.xlsx"))

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
files = list.files(pattern="table_file.txt")
files ="Pyclone_July2020_table_file.txt"

#data - table generated by pyclone (cluster)
files_cluster = list.files(pattern="cluster.txt")
files_cluster="Pyclone_July2020_table_file_cluster.txt"

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

#summary of mutation data
mut_gene = unique(read_only[,c("mut_id", "symbol", "biotype", "Func.ensGene", "ExonicFunc.ensGene",
"AAChange.ensGene", "cosmic68")])

pyclone_file= fread(files)

#how many mutations in each cluster?
cluster_sum = unique(pyclone_file[,c("cluster_id", "mutation_id")])

cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=2)
#still end up with 24 clusters here
#let's limit to the 10 clusters with the most mutations
cluster=cluster[order(-N)][1:10,]

#let's keep only the clusters with more than two mutations in them
pyclone_file = filter(pyclone_file, cluster_id %in% cluster$V1)

#to reduce speed problems with CITUP - for tree building let's just
#keep mutations in DLBCL driver genes
#first need to merge mut_id with which gene mutation is in
colnames(pyclone_file)[1] = "mut_id"
pyclone_file_merged = merge(pyclone_file, mut_gene, by="mut_id")

#now keep only the DLBCL ones
z = which(pyclone_file_merged$symbol %in% reddy$Gene)
pyclone_file_merged = pyclone_file_merged[z,]

#filter original file
pyclone_file = as.data.table(filter(pyclone_file, mut_id %in% pyclone_file_merged$mut_id))

muts = dcast(pyclone_file, cluster_id + mut_id ~ sample_id, value.var = "cellular_prevalence")
clusters = muts[,c(1:2)]

#mutation file
muts_final = muts[,3:ncol(muts)]
file = paste(date, "rap_citup_input_freqs.txt", sep="_")
write.table(muts_final, file, quote=F, row.names=F, col.names=F, sep="\t")

#cluster file
clusters = muts[,c("cluster_id")]
file = paste(date, "rap_citup_input_clusters.txt", sep="_")
write.table(clusters, file, quote=F, row.names=F, col.names=F, sep="\t")

#-----
#DONE-
#-----
