#-------------------------------------------------------------------------------
#pyclone-vi_005_pyclone_mutation_signatures_in_clusters.R
#Karin Isaev
#March 3rd 2021, 2021
#load R/4.0.0
#-------------------------------------------------------------------------------

#load packages and data
source("/cluster/home/kisaev/RAP_WGS/config-file.R")
library("gplots")
#library(MutationalPatterns)
library(BSgenome)
ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)
library(NMF)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(biomaRt)
library(GenomicRanges)
library(maftools)
#Requires BSgenome object
library(BSgenome.Hsapiens.UCSC.hg19, quietly = TRUE)
#library(logr)
library('pheatmap')

library(dplyr)
library(reshape2)
#library(kableExtra)
library(ggplot2)
library(gridExtra)
library(BSgenome.Hsapiens.UCSC.hg19)
hg19 <- BSgenome.Hsapiens.UCSC.hg19
library(ggpubr)
library(rjson)

# Load mutSignatures
#library(mutSignatures)
library(MutationalPatterns)

ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#set up patients
patients= c("LY_RAP_0001", "LY_RAP_0002", "LY_RAP_0003")

#test
#patient = "LY_RAP_0003"

z = which(read_only$Tissue_Site == "Aorta, ascending, not specified \n\n")
if(!(length(z) == 0)){
read_only$Tissue_Site[z] = "Aorta, ascending"}

#pyclone input files
p001_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0001_pyclone_input.tsv")
p002_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0002_pyclone_input.tsv")
p003_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0003_pyclone_input.tsv")

#pyclone output files
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone/26-09-2021")
p001_pyclone_output = fread("all_samples_pyclonevi_LY_RAP_0001_beta-binomial_rap_wgs_all_muts.tsv")
p002_pyclone_output = fread("all_samples_pyclonevi_LY_RAP_0002_beta-binomial_rap_wgs_all_muts.tsv")
p003_pyclone_output = fread("all_samples_pyclonevi_LY_RAP_0003_beta-binomial_rap_wgs_all_muts.tsv")

#pairtree clusters - files made manually
p001_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p001_pairtree_clones.txt")
p002_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p002_pairtree_clones.txt")
p003_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p003_pairtree_clones.txt")

#pairtree results json files
p001_pairtree_json = fromJSON(file="/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p001_solution.json")
p002_pairtree_json = fromJSON(file="/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p002_solution.json")
p003_pairtree_json = fromJSON(file="/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-24_input_files/min100_muts/final_chosen_tree/p003_solution.json")

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#use pyclone results clusters to identify mutation signatures associated
#with different clones

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

#test
#patient = patients[2]
#pyclone_output = p002_pyclone_output
#pairtree_cluster = p002_pairtree

get_mut_signatures = function(patient, pyclone_output, pairtree_cluster){

  #read in mutation data for each cluster as obtained from pyclone
  muts <- pyclone_output

  #get clusters
  clusters = unique(muts$cluster_id)

  #make folder to store plots for patient
  mainDir <- "/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone/clusters_mutation_signatures"
  subDir <- patient

  dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
  setwd(file.path(mainDir, subDir))

  #for each cluster gather mutations and their details from main mutation
  #file

  cluster_muts = unique(muts[,c("mutation_id", "cluster_id")])

  t = as.data.table(table(cluster_muts$cluster_id))
  t = filter(t, N >100)
  muts_keep = filter(cluster_muts, cluster_id %in% t$V1)
  colnames(t)= c("cluster_id", "num_muts")

  t=merge(t, pairtree_cluster)
  colnames(t)[3] = "pairtree_cluster_name"
  t$cluster_id = as.numeric(t$cluster_id)

  muts_keep = merge(muts_keep, t, by="cluster_id")

  mut.merged = as.data.table(filter(read_only, STUDY_PATIENT_ID == patient, mut_id %in% cluster_muts$mutation_id))
  mut.merged = unique(mut.merged[,c("mut_id", "ensgene", "POS", "CHROM", "symbol", "REF","ALT",
  "Gene.ensGene", "GeneDetail.ensGene", "ExonicFunc.ensGene", "Func.ensGene")])
  mut.merged$Variant_Classification = paste(mut.merged$Func.ensGene, mut.merged$ExonicFunc.ensGene)
  colnames(mut.merged)[1] = "mutation_id"

  mut.merged = merge(muts_keep, mut.merged, by="mutation_id")

  colnames(mut.merged)[6] = "start"
  mut.merged$end = mut.merged$start
  colnames(mut.merged)[7] = "chr"
  colnames(mut.merged)[8] = "Hugo_Symbol"
  mut.merged$Tumor_Sample_Barcode = patient

  print("pass")

  #use Mutational Patterns
  grl_my = makeGRangesListFromDataFrame(mut.merged, split.field ="pairtree_cluster_name", seqnames.field = "chr",
  start.field = "start", end.field = "end", keep.extra.columns=TRUE)

  print("pass2")
  type_occurrences <- mut_type_occurrences(grl_my, ref_genome)
  clones = as.numeric(rownames(type_occurrences))

  p_spec = plot_spectrum(type_occurrences, by = clones, CT = TRUE, legend = FALSE)

  pdf("mut_sigs_plot_spectrum.pdf", width=4, height=4)
  print(p_spec +
  theme(axis.text.x = element_text(size=4),
          axis.text.y = element_text(size=5),
          strip.text = element_text(size=4),
          panel.spacing = unit(.05, 'pt'),
          axis.title = element_text(size = 4),
        strip.text.x = element_text(margin = margin(0.1,0,0.1,0, "cm"))))
  dev.off()

  mut_mat <- mut_matrix(vcf_list = grl_my, ref_genome = ref_genome)

  pdf("mut_sigs_plot_96_profiles.pdf", width=4, height=4)
  p = plot_96_profile(mut_mat)
  print(p+
  theme(axis.text.x = element_text(size=4),
          axis.text.y = element_text(size=4),
          strip.text = element_text(size=4),
          panel.spacing = unit(.05, 'pt'),
          axis.title = element_text(size = 4),
        strip.text.x = element_text(margin = margin(0.1,0,0.1,0, "cm"))))
  dev.off()

  print("pass3")

  merged_signatures <- merge_signatures(signatures, cos_sim_cutoff = 0.5)

  print("pass4")

  #Fit mutation matrix to the COSMIC mutational signatures:
  strict_refit <- fit_to_signatures_strict(mut_mat, merged_signatures, max_delta = 0.008)
  fit_res_strict <- strict_refit$fit_res

  print("pass4")

  pdf("mutation_signature_analysis_plots.pdf", width=9, height=6)
  p1 = plot_contribution(fit_res_strict$contribution, palette=mypal, coord_flip=TRUE,
    signatures = merged_signatures, mode = "absolute")+
  theme(legend.title=element_text(size=5),
    legend.text=element_text(size=5))
  print(p1)

  p2 = plot_contribution(fit_res_strict$contribution, palette=mypal, coord_flip=TRUE)+
  theme(legend.title=element_text(size=5),
    legend.text=element_text(size=5))
  print(p2)

  dev.off()

  print("pass5")

  all_clusts = as.data.frame(fit_res_strict$contribution)
  all_clusts$signature = rownames(all_clusts)
  all_clusts=melt(as.data.table(all_clusts))
  all_clusts$patient = patient
  all_clusts = as.data.table(all_clusts)[order(-value)]

  print("pass6")

  setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
  return(all_clusts)
}

p001 = get_mut_signatures("LY_RAP_0001", p001_pyclone_output, p001_pairtree)
p002 = get_mut_signatures("LY_RAP_0002", p002_pyclone_output, p002_pairtree)
p003 = get_mut_signatures("LY_RAP_0003", p003_pyclone_output, p003_pairtree)

#combine all results
all_results = rbind(p001, p002, p003)
saveRDS(all_results, file="all_pyclone_clusters_signatures_results.rds")

#-----
#DONE-
#-----
