#-------------------------------------------------------------------------------
#pyclone-vi_005_pyclone_mutation_signatures_in_clusters.R
#Karin Isaev
#March 3rd 2021, 2021
#load R/4.0.0
#-------------------------------------------------------------------------------

#load packages and data
source("/cluster/home/kisaev/RAP_WGS/config-file.R")
library("gplots")
#library(MutationalPatterns)
library(BSgenome)
ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)
library(NMF)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(biomaRt)
library(GenomicRanges)
library(maftools)
#Requires BSgenome object
library(BSgenome.Hsapiens.UCSC.hg19, quietly = TRUE)
#library(logr)
library('pheatmap')

library(dplyr)
library(reshape2)
#library(kableExtra)
library(ggplot2)
library(gridExtra)
library(BSgenome.Hsapiens.UCSC.hg19)
hg19 <- BSgenome.Hsapiens.UCSC.hg19
library(ggpubr)

# Load mutSignatures
#library(mutSignatures)
library(MutationalPatterns)

ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#set up patients
patients= c("LY_RAP_0001", "LY_RAP_0002", "LY_RAP_0003")

#test
#patient = "LY_RAP_0003"

z = which(read_only$Tissue_Site == "Aorta, ascending, not specified \n\n")
if(!(length(z) == 0)){
read_only$Tissue_Site[z] = "Aorta, ascending"}

#pyclone input files
p001_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0001_pyclone_input.tsv")
p002_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0002_pyclone_input.tsv")
p003_pyclone_input = fread("all_samples_pyclonevi_LY_RAP_0003_pyclone_input.tsv")

#pyclone output files
p001_pyclone_output = fread("10-06-2021/all_samples_pyclonevi_LY_RAP_0001_beta-binomial_rap_wgs_all_muts.tsv")
p002_pyclone_output = fread("10-06-2021/all_samples_pyclonevi_LY_RAP_0002_beta-binomial_rap_wgs_all_muts.tsv")
p003_pyclone_output = fread("10-06-2021/all_samples_pyclonevi_LY_RAP_0003_beta-binomial_rap_wgs_all_muts.tsv")

#pairtree clusters - files made manually
p001_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-11_input_files/results2/p001_pairtree_clones.txt")
p002_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-11_input_files/results2/p002_pairtree_clones.txt")
p003_pairtree = fread("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pairtree/2021-06-11_input_files/results2/p003_pairtree_clones.txt")

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#use pyclone results clusters to identify mutation signatures associated
#with different clones

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

get_mapscape_input = function(patient, pyclone_output, pairtree_cluster){

  #read in mutation data for each cluster as obtained from pyclone
  muts <- pyclone_output

  #get clusters
  clusters = unique(muts$cluster_id)

  #make folder to store plots for patient
  mainDir <- "/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone/mapscape"
  subDir <- patient

  dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
  setwd(file.path(mainDir, subDir))

  #for each cluster gather mutations and their details from main mutation
  #file

  cluster_muts = unique(muts[,c("sample_id", "mutation_id", "cluster_id", "cellular_prevalence")])

  tt = unique(muts[,c("mutation_id", "cluster_id")])
  t = as.data.table(table(tt$cluster_id))
  t = filter(t, N >30)
  muts_keep = filter(cluster_muts, cluster_id %in% t$V1)
  colnames(t)= c("cluster_id", "num_muts")

  if(patient == "LY_RAP_0003"){
    t$num_muts[t$cluster_id == 4] = 93
  }

  t=merge(t, pairtree_cluster)
  colnames(t)[3] = "pairtree_cluster_name"
  t$cluster_id = as.numeric(t$cluster_id)
  muts_keep = merge(muts_keep, t, by="cluster_id")
  muts_keep = unique(muts_keep[,c("sample_id", "pairtree_cluster_name", "cellular_prevalence")])
  colnames(muts_keep) = c("sample_id", "clone_id", "clonal_prev")

  #figure out prevalence of "normal clone - 0"
  samples = unique(muts_keep$sample_id)
  zeroes = as.data.frame(matrix(nrow=1, ncol=3))
  colnames(zeroes) = c("sample_id", "clone_id", "clonal_prev")
  for(i in 1:length(samples)){
    clusts = filter(muts_keep, sample_id == samples[i])
    row = c(samples[i], 0, 1)
    zeroes = rbind(zeroes,row)
  }

  zeroes = zeroes[-1,]
  muts_keep = rbind(muts_keep, zeroes)
  muts_keep$clone_id = as.numeric(muts_keep$clone_id)
  muts_keep$clonal_prev = as.numeric(muts_keep$clonal_prev)

  write.table(muts_keep, file="mapscape_input_from_pairtree_pyclonevi.txt", quote=F, row.names=F, sep="\t")

  setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
  print("done")
}

get_mapscape_input("LY_RAP_0001", p001_pyclone_output, p001_pairtree)
get_mapscape_input("LY_RAP_0002", p002_pyclone_output, p002_pairtree)
get_mapscape_input("LY_RAP_0003", p003_pyclone_output, p003_pairtree)

#-----
#DONE-
#-----
