#-------------------------------------------------------------------------------
#pyclone-vi_005_pyclone_mutation_signatures_in_clusters.R
#Karin Isaev
#March 3rd 2021, 2021
#load R/4.0.0
#-------------------------------------------------------------------------------

#load packages and data
source("/cluster/home/kisaev/RAP_WGS/config-file.R")
library("gplots")
#library(MutationalPatterns)
library(BSgenome)
ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)
library(NMF)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(biomaRt)
library(GenomicRanges)
library(maftools)
#Requires BSgenome object
library(BSgenome.Hsapiens.UCSC.hg19, quietly = TRUE)
#library(logr)
library('pheatmap')

library(dplyr)
library(reshape2)
#library(kableExtra)
library(ggplot2)
library(gridExtra)
library(BSgenome.Hsapiens.UCSC.hg19)
hg19 <- BSgenome.Hsapiens.UCSC.hg19

# Load mutSignatures
#library(mutSignatures)
library(MutationalPatterns)

ref_genome <- "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#set up patients
patients= c("LY_RAP_0001", "LY_RAP_0002", "LY_RAP_0003")

#test
#patient = "LY_RAP_0003"

z = which(read_only$Tissue_Site == "Aorta, ascending, not specified \n\n")
if(!(length(z) == 0)){
read_only$Tissue_Site[z] = "Aorta, ascending"}

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#use pyclone results clusters to identify mutation signatures associated
#with different clones

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#test
patient_clonevol_results="LY_RAP_0001_all_mutations_Pyclone-VI-clonevol-results.xlsx"
patient = "LY_RAP_0001"

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

get_mut_signatures = function(patient, patient_clonevol_results){

  #read in mutation data for each cluster as obtained from pyclone
  muts <- as.data.table(read_excel(patient_clonevol_results))

  #keep only clusters that were included in the tree
  z = which(muts$cluster_removed == "removed")
  muts = muts[-z,]

  #get clusters
  clusters = unique(muts$cluster)

  #make folder to store plots for patient
  mainDir <- "/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone/clusters_mutation_signatures"
  subDir <- patient

  dir.create(file.path(mainDir, subDir), showWarnings = FALSE)
  setwd(file.path(mainDir, subDir))

  #for each cluster gather mutations and their details from main mutation
  #file

  cluster_muts = unique(muts[,c("mut_id", "cluster")])
  mut.merged = as.data.table(filter(read_only, STUDY_PATIENT_ID == patient, mut_id %in% cluster_muts$mut_id))
  mut.merged = unique(mut.merged[,c("mut_id", "ensgene", "POS", "CHROM", "symbol", "REF","ALT",
  "Gene.ensGene", "GeneDetail.ensGene", "ExonicFunc.ensGene", "Func.ensGene")])
  mut.merged$Variant_Classification = paste(mut.merged$Func.ensGene, mut.merged$ExonicFunc.ensGene)
  mut.merged = merge(cluster_muts, mut.merged, by="mut_id")

  colnames(mut.merged)[4] = "start"
  mut.merged$end = mut.merged$start
  colnames(mut.merged)[5] = "chr"
  colnames(mut.merged)[6] = "Hugo_Symbol"
  mut.merged$Tumor_Sample_Barcode = patient

  #use Mutational Patterns
  grl_my = makeGRangesListFromDataFrame(mut.merged, split.field ="cluster", seqnames.field = "chr",
  start.field = "start", end.field = "end", keep.extra.columns=TRUE)
  mut_mat <- mut_matrix(vcf_list = grl_my, ref_genome = ref_genome)

  merged_signatures <- merge_signatures(signatures, cos_sim_cutoff = 0.8)

  #Fit mutation matrix to the COSMIC mutational signatures:
  strict_refit <- fit_to_signatures_strict(mut_mat, merged_signatures, max_delta = 0.004)
  fit_res_strict <- strict_refit$fit_res

  pdf("mutation_signature_analysis_plots.pdf")
  p = plot_contribution(fit_res_strict$contribution, palette=mypal)
  print(p)
  dev.off()

  all_clusts = as.data.frame(fit_res_strict$contribution)
  all_clusts$signature = rownames(all_clusts)
  all_clusts=melt(as.data.table(all_clusts))
  all_clusts$patient = patient
  all_clusts = as.data.table(all_clusts)[order(-value)]

  setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")
  return(all_clusts)
}

p001 = get_mut_signatures("LY_RAP_0001", "LY_RAP_0001_all_mutations_Pyclone-VI-clonevol-results.xlsx")
p002 = get_mut_signatures("LY_RAP_0002", "LY_RAP_0002_all_mutations_Pyclone-VI-clonevol-results.xlsx")
p003 = get_mut_signatures("LY_RAP_0003", "LY_RAP_0003_all_mutations_Pyclone-VI-clonevol-results.xlsx")

#combine all results
all_results = rbind(p001, p002, p003)
saveRDS(all_results, file="all_pyclone_clusters_signatures_results.rds")

#-----
#DONE-
#-----
