#----------------------------------------------------------------------
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#load functions and libraries
#----------------------------------------------------------------------

options(stringsAsFactors=F)

#load libraries
packages <- c("dplyr", "readr", "ggplot2", "vcfR", "tidyr", "mclust", "data.table",
              "plyr", "clonevol", "readxl", "pheatmap",
              "ggrepel", "stringr", "maftools", "magrittr", "ggExtra", "cowplot")
lapply(packages, require, character.only = TRUE)

date = Sys.Date()

#----------------------------------------------------------------------
#purpose
#----------------------------------------------------------------------

#use pyclone clustering results from small subset of mutations to
#generate tree

#----------------------------------------------------------------------
#data
#----------------------------------------------------------------------

#Our mutations
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/merged_MUTECT2_STRELKA/merged_variants_vcfs/vcf_summary_text")
read_only = readRDS(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.rds")[length(list.files(pattern="READ_ONLY_ALL_MERGED_MUTS.rds"))])

setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#sample info
samps = readRDS("/cluster/projects/kridelgroup/RAP_ANALYSIS/copy_RAP_masterlist_samples.rds")
colnames(samps)[4] ="Indiv"
z = which(samps$Indiv %in% read_only$Indiv)
samps = samps[z,]
samps[18,2] = "Kidney, NOS 2"

read_only$Tissue_Site = NULL
read_only$STUDY_PATIENT_ID = NULL
read_only$Specimen_Type = NULL

read_only = merge(read_only, samps, by = "Indiv")

#DLBCL driver genes from Reddy et al 2017
reddy = as.data.table(read_excel("/cluster/projects/kridelgroup/RAP_ANALYSIS/data/Reddyetal_2017_driver_mutations.xlsx"))

#data - table generated by pyclone (loci)
setwd("/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/Pyclone")

#results from pyclone-vi
patients= c("LY_RAP_0001", "LY_RAP_0002", "LY_RAP_0003")

patient = "LY_RAP_0003" #test

#----------------------------------------------------------------------
#analysis
#----------------------------------------------------------------------

get_patient_pyclone_plot = function(patient){

  #get results from pyclone
  file_name = paste(patient, "_rap_wgs_subset_muts.tsv", sep="")
  vi=fread(file_name)

  #summary of mutation data
  mut_gene = unique(read_only[,c("mut_id", "symbol", "biotype", "Func.ensGene", "ExonicFunc.ensGene",
    "AAChange.ensGene", "cosmic68", "STUDY_PATIENT_ID")])
  mut_gene = as.data.table(filter(mut_gene, STUDY_PATIENT_ID == patient))
  mut_gene = unique(mut_gene[,c("mut_id", "symbol", "biotype", "Func.ensGene", "ExonicFunc.ensGene",
    "AAChange.ensGene", "cosmic68")])

  #pyclone_file= fread(files)
  pyclone_file=vi

  #how many mutations in each cluster?
  cluster_sum = unique(pyclone_file[,c("cluster_id", "mutation_id")])

  #for these plots keep original pyclone clusters and mutations

#  if(patient == "LY_RAP_0001"){
#    cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=10)
#    pyclone_remove=c()
#  }

#  if(patient == "LY_RAP_0002"){
#    cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=100)
    #remove clusters with low cluster_assignment_prob
    #pyclone_remove = unique(as.data.table(filter(pyclone_file, (cluster_assignment_prob < 0.5) | (is.na(cellular_prevalence_std))))$cluster_id)
#    pyclone_remove=c()
#  }

#  if(patient == "LY_RAP_0003"){
#    cluster = filter(as.data.table(table(cluster_sum$cluster_id)), N >=15)
    #remove clusters with low cluster_assignment_prob
    #pyclone_remove = unique(as.data.table(filter(pyclone_file, (cluster_assignment_prob < 0.5) | (is.na(cellular_prevalence_std))))$cluster_id)
#    pyclone_remove=c()
#  }

#  pyclone_file = filter(pyclone_file, cluster_id %in% cluster$V1, !(cluster_id %in% pyclone_remove))
  colnames(pyclone_file)[1] = "mut_id"
  pyclone_file_merged = merge(pyclone_file, mut_gene, by="mut_id")

  #ClonEvol requires an input data frame consisting of at least a
  #cluster column and one or more variant cellular prevalence columns,
  #each corresponds to a sample.
  samps = as.data.frame(unique(pyclone_file_merged$sample_id))
  colnames(samps)[1] = "sample_id"
  samps$sample = ""

  for(i in 1:length(unique(samps$sample_id))){
    print(i)
    tissue = read_only$Tissue_Site[read_only$Sample == samps$sample_id[i]][1]
    samps$sample[i] = tissue
  }

  pyclone_file_merged = merge(pyclone_file_merged, samps, by="sample_id")
  pyclone_file_merged$vaf_fixed = pyclone_file_merged$cellular_prevalence /2 *100

  summaries_vafs_fixed = as.data.table(pyclone_file_merged %>%
    group_by(sample, cluster_id) %>%
    dplyr::summarize(mean=mean(cellular_prevalence)))

  summaries_vafs_fixed = dcast(summaries_vafs_fixed, sample ~ cluster_id,
      value.var = "mean")

  rownames(summaries_vafs_fixed) = summaries_vafs_fixed$sample
  summaries_vafs_fixed$sample = NULL
  summaries_vafs_fixed = as.matrix(summaries_vafs_fixed)
  col<- colorRampPalette(c("red", "white", "blue"))(256)

  #for each cluster and sample get mean cell prev
  mean_cp_clusters = as.data.table(pyclone_file_merged %>% group_by(sample_id, cluster_id) %>%
  dplyr::summarize(mean_cp=mean(cellular_prevalence)))
  mean_cp_clusters$cluster_id = factor(mean_cp_clusters$cluster_id)
  mean_cp_clusters$sample_name = sapply(mean_cp_clusters$sample_id,
    function(x){unlist(strsplit(x, "_subset_muts_pyclone_input"))[1]})
  mean_cp_clusters = mean_cp_clusters[order(-mean_cp)]
  mean_cp_clusters$cluster_id = factor(mean_cp_clusters$cluster_id, levels=unique(mean_cp_clusters$cluster_id))

  dir.create(paste(patient, "pyclone_subset_runs_plots", sep="_"))
  setwd(paste(patient, "pyclone_subset_runs_plots", sep="_"))

  pdf(paste(patient, 'subset_list_pyclone_cell_prev.pdf', sep="_"), width = 10, height = 6, useDingbats = FALSE)
  p = ggplot(mean_cp_clusters, aes(x=cluster_id, y=mean_cp, group=sample_name)) +
    geom_line(aes(color=sample_name))+
    geom_point(aes(color=sample_name))
  p = p + theme_minimal()
  p = p + theme(legend.position="bottom")+ theme(legend.text=element_text(size=4))
  print(p)
  dev.off()

  #geom tile
  pdf(paste(patient, "summary_subset_list_pyclone_cell_prev_tiles.pdf", sep="_"), width=9, height=6)
  g = ggplot(mean_cp_clusters, aes(x=cluster_id, y=sample_name)) +
  geom_tile(aes(fill=mean_cp,width=0.75, height=0.75),size=0.55, colour = "black")+
  scale_fill_gradient(low = "grey", high = "purple", na.value = 'white')
  print(g)
  dev.off()

}#end function patient input

p001_dat = get_patient_pyclone_plot("LY_RAP_0001")
p002_dat = get_patient_pyclone_plot("LY_RAP_0002")
p003_dat = get_patient_pyclone_plot("LY_RAP_0003")
#-----
#DONE-
#-----
