__default__:
    partition:  himem # users specified
    mem:    60000M
    time:   "5-00:00"
    ncpus:  4
    out:  "/cluster/projects/kridelgroup/RAP_ANALYSIS/ANALYSIS/ConsensusCruncher/slurm_outputs/%x-%j.out"
